### ISSUE TITLE
OpenSim is misusing the SimTK::ReferencePtr class in many places

### ISSUE THREAD

**Issue by sherm1** [opensim-org/opensim-core#528] opened 2015-07-13 03:26 UTC
`SimTK::ReferencePtr` is a smart pointer that conveys *no* ownership. It is used to point at things owned by someone else. It is better than a raw pointer because it self-initializes to `nullptr` and clear itself back to `nullptr` on copy to avoid dangling references from the copy. The point of it is to allow us to avoid writing copy constructors and copy assignment, as we would have to if we used raw pointers.

But since there is no ownership it is *never* OK to invoke `delete` on a `ReferencePtr`! Nor should a `ReferencePtr` ever be set to `new Something()`! There are many instances of both of these errors and they will start producing warnings when PR simbody/simbody#410 is merged. They will have to be fixed very carefully.

**Comment by sherm1** [comment] 2015-07-13 05:07
Broken `ReferencePtr`: 
ControllerSet::_controlStore
CoordinateLimitForce::_upStep, _loStep
GeometryPath::_maSolver
Model::_assemblySolver,_modelViz,_contactSubsystem,_gravityForce,_forceSubsystem,_matter,_system

**Comment by chrisdembia** [comment] 2015-07-13 06:37
I see you didn't put Coordinate::_lockFunction in your list:

https://github.com/opensim-org/opensim-core/pull/510/files
https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/Coordinate.h#L309

This is a case where a ReferencePtr is set to `new Something()`, but the pointer is passed to a class that will take ownership of the pointer. In this case, it's still nice to have the ReferencePtr so that the pointer is set to `nullptr` upon copy. What should be done here?

**Comment by sherm1** [comment] 2015-07-13 16:19
> I see you didn't put Coordinate::_lockFunction in your list

Thanks, that's an interesting case I didn't notice. It is still a misuse (temporarily) because the ReferencePtr is used to hold ownership until it can be transferred. After that it really is just a reference to someone else's object so is OK. This is likely harmless here but would cause a leak if an exception occurred before the ownership could be transferred, since a ReferencePtr will not destruct its contents.

A nicer way to do this I think would be to use an `std::unique_ptr` to hold the freshly-allocated `Function` object until its ownership can be transferred to the `PrescribedMotion` constraint. It would look something like this:
```c++
std::unique_ptr<Function> func(new Function()); // func has ownership
ReferencePtr<Function> funcref(func.get()); // keep a reference to Function object
Constraint::PrescribedMotion(func.release()); // take over ownership from func
```

**Comment by chrisdembia** [comment] 2015-07-13 18:50
I didn't know about `release()`! Thanks.

**Comment by sherm1** [comment] 2015-07-14 21:27
Note: when this is closed, fix issue #532 also.

**Comment by chrisdembia** [comment] 2015-07-25 20:57
Potentially related: #102, #106.

**Comment by chrisdembia** [comment] 2015-07-26 17:20
I'm trying to fix `ReferencePtr<SimTK::Function::Step> CoordinateLimitForce::_upStep`, and `_loStep`. From my understanding of the code, these should be `ClonePtr`'s. The issue is that `SimTK::Function::Step` does not have a `clone()` method. I see 3 solutions:

1. I can use `unique_ptr` and manually define a copy constructor, etc. to do the cloning.
2. ClonePtr's could use `new T()` instead of `obj.clone()` when making the copy. I expect there's a reason why this isn't a good idea though.
3. `SimTK::Function::Step` could get a `clone()`.

What do you think is best?

**Comment by chrisdembia** [comment] 2015-07-26 23:20
@sherm1, I'm not sure what to do for `GeometryPath::_maSolver`: this object *is* owned by GeometryPath, but it cannot be constructed when the GeometryPath is constructed (since the MomentArmSolver needs a Model). This means we cannot use a ClonePtr. However, we need the pointer to be cleared upon copy, and that's why I think the ReferencePtr was used. So we need a `unique_cleared_on_copy` pointer, some mix of `unique_ptr` and `ReferencePtr`.

**Comment by sherm1** [comment] 2015-07-27 00:51
> I'm not sure what to do for GeometryPath::_maSolver: this object is owned by GeometryPath, but ... the MomentArmSolver needs a Model

Sounds like MomentArmSolver should have a ReferencePtr<Model>. Then `_maSolver` could be a ClonePtr<MomentArmSolver> which would automatically copy but then the copied MomentArmSolver would nave a null Model.

**Comment by sherm1** [comment] 2015-07-27 01:32
> The issue is that SimTK::Function::Step does not have a clone() method. I see 3 solutions:
> I can use unique_ptr and manually define a copy constructor, etc. to do the cloning.

That could work but is a move in the wrong direction since we would like to get rid of those. You can tell the code is currently bad though because there is a non-default destructor, yet no copy constructor or copy assignment. That is almost never right.

> ClonePtr's could use new T() instead of obj.clone() when making the copy. I expect there's a reason why this isn't a good idea though.

Yes, that can't work because T is typically an abstract class and can't be constructed. What's needed is a "virtual copy constructor" and such a thing does not exist in C++. `clone()` is the standard solution.

> SimTK::Function::Step could get a clone().

I think that is the right idea, but I don't think it has to be done that way. Looking at the code, I think SimTK::Function::Step is just an ordinary object that can be copied and assigned (like an int!). So I think the problem would be cured if _upStep and _loStep were of type SimTK::Function::Step rather than pointers (they would have to be given some default values on construction because there is no default constructor). Then `extendConnectToModel()` would just do
```c++
_loStep = SimTK::Function::Step(y0,y1,x0,x1);
```
and this would get copied properly by the default copy constructor. We could also add a method to Function::Step that would allow changing the four parameters; currently that can only be done at construction.

**Comment by chrisdembia** [comment] 2015-07-27 03:05
Thanks @sherm1 . I tried that and the issue is that the copy assignment for `Function::Step` is deleted because it has const member variables?

```cpp
/Users/chris/repos/opensim/6/opensim-core/OpenSim/Simulation/Model/CoordinateLimitForce.h:56:1: error: object of type 'OpenSim::CoordinateLimitForce' cannot be assigned
      because its copy assignment operator is implicitly deleted
OpenSim_DECLARE_CONCRETE_OBJECT(CoordinateLimitForce, Force);
^
/Users/chris/repos/opensim/6/opensim-core/OpenSim/Common/Object.h:1031:80: note: expanded from macro 'OpenSim_DECLARE_CONCRETE_OBJECT'
#define OpenSim_DECLARE_CONCRETE_OBJECT(ConcreteClass, SuperClass)             \
                                                                               ^
/Users/chris/repos/opensim/6/opensim-core/OpenSim/Common/Object.h:1088:80: note: expanded from macro '\
OpenSim_OBJECT_ANY_DEFS'
typedef SuperClass    Super;                                                   \
                                                                               ^
/Users/chris/repos/opensim/6/opensim-core/OpenSim/Common/Object.h:1134:17: note: expanded from macro '\
OpenSim_OBJECT_JAVA_DEFS'
          *this = *((thisClass*)(&aObject)); \
                ^
/Users/chris/repos/opensim/6/opensim-core/OpenSim/Simulation/Model/CoordinateLimitForce.h:240:27: note: copy assignment operator of 'CoordinateLimitForce' is implicitly
      deleted because field '_upStep' has a deleted copy assignment operator
    SimTK::Function::Step _upStep;
                          ^
/Users/chris/repos/simbody/4/install/include/simbody/SimTKcommon/internal/Function.h:402:16: note: copy assignment operator of 'Step' is implicitly deleted because field
      'm_y0' is of const-qualified type 'const double'
    const T    m_y0, m_y1, m_yr;   // precalculate yr=(y1-y0)
```

See [this branch](https://github.com/opensim-org/opensim-core/tree/refptr-misuse-coordinatelimitforce) for the changes.

**Comment by sherm1** [comment] 2015-07-27 15:28
> I tried that and the issue is that the copy assignment for Function::Step is deleted 

Oh! OK, I'll fix that and then your change should work.

**Comment by chrisdembia** [comment] 2015-07-27 17:18
I want to post an update about Model: `_modelViz` and `_assemblySolver` are both objects that are:

1. owned by Model
2. are not constructed when the Model is constructed OR should not necessarily exist (`_modelViz` should only be constructed if the user asks to use the visualizer).
3. that should not be copied when copying the Model (or couldn't be, based on 2 above).

It's evident why these were turned into ReferencePtr's (for the nulling upon copy). Not sure yet what to do with these though. 

For `_assemblySolver`, I think we can avoid allocating on the heap and construct a dummy AssemblySolver when the Model is constructed. I'm not sure we can do the same thing for `_modelViz`.

**Comment by sherm1** [comment] 2015-07-27 17:41
Regarding `CoordinateLimitForce`: see PR simbody/simbody#416.

**Comment by sherm1** [comment] 2015-07-27 18:16
> I want to post an update about Model: _modelViz and _assemblySolver (owned by Model). It's evident why these were turned into ReferencePtr's (for the nulling upon copy). 

It does seem like we need another smart pointer that would be the same as `std::unique_ptr` but add copy construction and assignment that would null the destination like `ReferencePtr` does. I think this would be easy to derive from `std::unique_ptr`. What would be a good name? `ResetOnCopyUniquePtr<T>` or something like that?

**Comment by sherm1** [comment] 2015-07-27 18:34
@klshrinidhi may have some thoughts on this. Shrinidhi, we have some classes like OpenSim::Model that own some private, heap-allocated objects (like a Visualizer and AssemblySolver, see above). Model is copyable, but these owned objects shouldn't get copied because they contain references into their parent Model. We just want the new copy to have nulls for them, so it can create new ones that point into the copy rather than the original. We would like to make this happen without having to write a copy constructor or copy assignment for Model. We have ReferencePtr that does this for non-owned pointers and are thinking we might need another smart pointer that conveys ownership like std::unique_ptr but produces nulls when copied, maybe `ResetOnCopyUniquePtr<T>`. Questions:
- is there a better way to handle this problem?
- if we need a new smart pointer is that a good name for it?
- any other thoughts/comments/advice on this?

**Comment by klshrinidhi** [comment] 2015-07-27 18:51
Problem -- The class Model needs special copy semantics that defaulted copy constructor does not cover. 

Some code has to be written to implement the appropriate semantics. The question is where to write the code:
* In the copy constructor for Model.
* In a separate (smart pointer) class's copy constructor. This class can then become a member of Model eliminating the need for a copy constructor in Model itself.

It don't see any other option. The second option makes the semantics reusable in other classes as well without writing any code but it also adds extra indirection (through pointer) for accessing the "pointed to" objects.

I think your suggestion or `NullOnCopyUniquePtr` for name is descriptive enough. 

This class will also need offer a move constructor just like `std::unique_ptr` if I am correct.

**Comment by sherm1** [comment] 2015-07-27 19:32
Thanks, Shrinidhi -- that's a very concise and helpful analysis! I am thinking the new smart pointer could inherit from std::unique_ptr for most functionality. I *think* it would get default move construction that would invoke std::unique_ptr move construction but I'm not sure. I agree that it needs move semantics and that those should *not* be null-producing.

**Comment by klshrinidhi** [comment] 2015-07-27 19:41
Deriving `public`ly from `std::unique_ptr` is my first thought as well. The copy constructor of the derived class can probably just have empty body. This will call the default constructor of 'std::unique_ptr' and so will end up creating a null pointer upon copy.

**Comment by sherm1** [comment] 2015-07-27 19:46
(An aside: I just noticed that the rule "if there's a destructor defined, there ought to be a copy constructor & copy assignment defined also" has a name and wikipedia page: ["the rule of 3"](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)). It is modified to "rule of five" for C++11 to include move construction and assignment.)

**Comment by sherm1** [comment] 2015-07-27 21:56
PR simbody/simbody#416 is now merged with Function assigning and cloning; you can retry CoordinateLimitForce fix whenever. I'm working on NullOnCopyUniquePtr.

**Comment by chrisdembia** [comment] 2015-07-27 22:00
Okay thank you.

**Comment by chrisdembia** [comment] 2015-07-31 21:28
Progress on @sherm1's list above:

- [x] ControllerSet::_controlStore
- [ ] CoordinateLimitForce::_upStep, _loStep (PR submitted, perhaps ready to be merged)
- [x] GeometryPath::_maSolver
- [ ] Model::_assemblySolver,_modelViz, _contactSubsystem, _gravityForce,_forceSubsystem, _matter,_system (waiting until we move to VS2015).

**Comment by sherm1** [comment] 2015-07-31 21:39
Yes, I forgot to merge #561. Done now.

**Comment by chrisdembia** [comment] 2015-08-13 19:46
I'll wrap up the Model changes once @sherm1 decides if he wants to update his new mixins for Simbody handle classes.

**Comment by sherm1** [comment] 2015-08-14 23:28
New mixins `ResetOnCopy<T>` and `ReinitOnCopy<T>` are available now that PR simbody/simbody#426 is merged. Please consider `NullOnCopyUniquePtr` deprecated since `ResetOnCopy<unique_ptr<T>>` does the same thing in a better way and can be used with many other types.

**Comment by chrisdembia** [comment] 2015-08-16 22:44
I'm trying to move `Model::_assemblySolver` to `ResetOnCopy<unique_ptr<AssemblySolver>>` but if I do this, then I can no longer simply forward-declare the AssemblySolver; I must also include it. This might be avoided if the implementation of the new mixins is moved to a cpp file?

**Comment by sherm1** [comment] 2015-08-17 01:17
> I can no longer simply forward-declare the AssemblySolver; I must also include it. 

Only forward declare should be required since only a pointer is kept by unique_ptr. And ResetOnCopy doesn't even see that since it is templatized on the unique_ptr rather than the underlying pointer. This needs further investigation; I'll try an experiment.

> This might be avoided if the implementation of the new mixins is moved to a cpp file?

Can't be done because these are templates. The definitions must be visible.

**Comment by sherm1** [comment] 2015-08-17 01:24
Oh wait, this is probably because you are now destructing the AssemblySolver in a context where it is an incomplete class. You can't do that because C++ can't know what destructor to call, or even whether AssemblySolver has a destructor. You just have to make sure that the destruction occurs in a context where the definition is visible. That might mean that `~Model()`'s implementation must be in Model.cpp rather than Model.h. This should work:
```c++
// Model.h
class AssemblySolver;
class Model {
    ~Model();
    ResetOnCopy<unique_ptr<AssemblySolver>> _assemblySolver;
};
// Model.cpp
#include "AssemblySolver.h"
Model::~Model() {}
```

Does it?

**Comment by sherm1** [comment] 2015-08-17 01:44
Rats, I tried the following experiment and it wants a definition of AssemblySolver:
```c++
class AssemblySolver;
class Model {
public:
    ~Model();
    std::unique_ptr<AssemblySolver> m_solver;
};

void testit() {
    Model m;
}
```

Note that I didn't use ResetOnCopy at all -- just unique_ptr.

**Comment by sherm1** [comment] 2015-08-17 02:11
OK, I think I have it now. This compiles fine:
```c++
class AssemblySolver;
class Model {
public:
    ~Model();
    Model();
    ResetOnCopy<unique_ptr<AssemblySolver>> m_solver;
};

void testit() {
    Model m;
}
```

The only difference from the earlier one is that I also moved the `Model()` default constructor out of the header. Apparently it is unique_ptr's default constructor that is using the definition of AssemblySolver.

**Comment by sherm1** [comment] 2015-08-17 02:24
Also I didn't have the same problem with unique_ptr in gcc or clang -- did you see it there or just in VS?

**Comment by chrisdembia** [comment] 2015-08-21 17:54
Thanks for testing those things out @sherm1. I've only tested in clang. It seems like the issue is much more complex. Here's the compiler error I get:

```
[ 17%] Building CXX object OpenSim/Simulation/CMakeFiles/osimSimulation.dir/InverseDynamicsSolver.cpp.o
In file included from /Users/chris/repos/opensim/7/opensim-core/OpenSim/Simulation/InverseDynamicsSolver.cpp:24:
In file included from /Users/chris/repos/opensim/7/opensim-core/OpenSim/Simulation/InverseDynamicsSolver.h:26:
In file included from /Users/chris/repos/opensim/7/opensim-core/OpenSim/Simulation/Solver.h:27:
In file included from /Users/chris/repos/opensim/7/opensim-core/OpenSim/Common/Object.h:39:
In file included from /Users/chris/repos/opensim/7/opensim-core/OpenSim/Common/XMLDocument.h:32:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2429:27: error: invalid application of 'sizeof' to an incomplete type 'OpenSim::AssemblySolver'
            static_assert(sizeof(_Tp) > 0, "default_delete can not delete incomplete type");
                          ^~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2630:13: note: in instantiation of member function 'std::__1::default_delete<OpenSim::AssemblySolver>::operator()' requested here
            __ptr_.second()(__tmp);
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2598:46: note: in instantiation of member function 'std::__1::unique_ptr<OpenSim::AssemblySolver, std::__1::default_delete<OpenSim::AssemblySolver> >::reset' requested
      here
    _LIBCPP_INLINE_VISIBILITY ~unique_ptr() {reset();}
                                             ^
/Users/chris/repos/simbody/4/install/include/simbody/SimTKcommon/internal/ResetOnCopy.h:45:7: note: in instantiation of member function 'std::__1::unique_ptr<OpenSim::AssemblySolver, std::__1::default_delete<OpenSim::AssemblySolver> >::~unique_ptr' requested here
class ResetOnCopyHelper {};
      ^
/Users/chris/repos/opensim/7/opensim-core/OpenSim/Simulation/Model/Model.h:73:7: note: forward declaration of 'OpenSim::AssemblySolver'
class AssemblySolver;
      ^
1 error generated.
```

The error is not related to compiling Model.cpp; it comes up when including `<iostream>`, perhaps in a cpp file that also includes Model.h? I'm not really sure.... Could this have to do with two-pass template stuff?

**Comment by sherm1** [comment] 2015-08-21 18:06
> The error is not related to compiling Model.cpp ... perhaps in a cpp file that also includes Model.h?

Looks like it happened in InverseDynamicsSolver.cpp. I *think* this is because some inline method in Model.h requires access to `~AssemblySolver`. This could be something like `Model() {}` in the header, or one of the default-generated methods. My suggestion is to look for those and move their definitions to Model.cpp, not because Model.cpp is a problem but because Model.h is a problem.

**Comment by chrisdembia** [comment] 2015-08-21 19:04
Model's constructors and destructor are defined in the cpp file, and it uses the default copy constructor, etc.

**Comment by sherm1** [comment] 2015-08-21 19:59
> Model's constructors and destructor are defined in the cpp file, and it uses the default copy constructor, etc.

I'm sure we could wrestle this to the ground with some effort, but it might be more practical just to look at getting the `AssemblySolver` definition visible to the `Model` declaration so that `std::unique_ptr<AssemblySolver>` won't freak out. Can you do that instead?

**Comment by chrisdembia** [comment] 2015-09-03 04:49
I think we've resolved this issue. If we find any other misuse we can reopen.

Here are some of the related PR's: #595 #585, #560 #553

**Closed by chrisdembia** 2015-09-03 04:49 UTC
Labels: bug
