### ISSUE TITLE
Static Optimization

### ISSUE THREAD

**Issue by mshabani** [opensim-org/opensim-core#1264] opened 2016-09-19 18:35 UTC
StaticOptimizationTarget.cpp has compilation errors when USE_LINEAR_CONSTRAINT_MATRIX is not defined. Error is due to bad call to computeConstraintVector() in constraintFunc. it needs state as a parameter.

**Comment by klshrinidhi** [comment] 2016-09-19 18:39
Please post details of how you built the sources -- OS, compiler, build-flags etc. And please post the error message you are getting verbatim.

**Comment by mshabani** [comment] 2016-09-19 18:49
Here is error along with warnings. I built opensim from github core with default flags on Windows. I think it's a bad function call and not related to flags or OS.

Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	C2660	'OpenSim::StaticOptimizationTarget::computeConstraintVector': function does not take 2 arguments	osimAnalyses	C:\workspace\opensim_core\src\OpenSim\Analyses\StaticOptimizationTarget.cpp	558	Build	
Warning	C4068	unknown pragma	osimAnalyses	C:\workspace\opensim_core\src\OpenSim\Common\Component.h	1620	Build	
Warning	C4068	unknown pragma	osimAnalyses	C:\workspace\opensim_core\src\OpenSim\Common\Component.h	1617	Build	
Warning	C4068	unknown pragma	osimAnalyses	C:\workspace\opensim_core\src\OpenSim\Common\Component.h	1616	Build	
Error (active)		too few arguments in function call	osimAnalyses	c:\workspace\opensim_core\src\OpenSim\Analyses\StaticOptimizationTarget.cpp	558	IntelliSense	
Error (active)		a reference of type "SimTK::State &" (not const-qualified) cannot be initialized with a value of type "const SimTK::Vector"	osimAnalyses	c:\workspace\opensim_core\src\OpenSim\Analyses\StaticOptimizationTarget.cpp	558	IntelliSense

**Comment by klshrinidhi** [comment] 2016-09-19 18:51
Did you make any edits to the source code ? If yes, please post the details.
We need enough information to reproduce the problem.

**Comment by tkuchida** [comment] 2016-09-19 19:01
Has the `#define USE_LINEAR_CONSTRAINT_MATRIX` line at the top of StaticOptimizationTarget.cpp been commented out?

**Comment by mshabani** [comment] 2016-09-19 19:01
In StaticOptimizationTarget.cpp remove line 47 : #define USE_LINEAR_CONSTRAINT_MATRIX
This will produce the error.
When this is defined, it builds constraint matrix and everything works fine. But when USE_LINEAR_CONSTRAINT_MATRIX is not defined, it is supposed to evaluate constraint vectors and error happens in line 558 due to bad call to computeConstraintVector:
computeConstraintVector(parameters,constraints);
It should take state as input like : 
computeConstraintVector(s, parameters,constraints);

**Comment by mshabani** [comment] 2016-09-19 19:02
@tkuchida  yes

**Comment by chrisdembia** [comment] 2016-09-19 20:14
Thanks for reporting, @mshabani. What led you to choose to undefine  `USE_LINEAR_CONSTRAINT_MATRIX`? Were you adapting that code for another purpose? Since we do not ever undefine `USE_LINEAR_CONSTRAINT_MATRIX`, I have little confidence that that code path would do the right thing.

Could you explain what your larger goal is, so we can prioritize a bug fix? If you think you can fix this bug, that would be great as well; let us know if you have a proposal for how to address it. Even if the compilation error is fixed, there still might be some  testing required to ensure that code path is correct.

**Comment by mshabani** [comment] 2016-09-20 18:44
The general idea is to add new constraints to the static optimizer and I thought it would be nice to try it with out linearization matrix so that's why I undefined USE_LINEAR_CONSTRAINT_MATRIX.
This might work: There is a _currentState variable defined in StaticOptimizationTarget.h which can be used in this case like : 
StaticOptimizationTarget.h
line 58: SimTK::State* _currentState;

StaticOptimizationTarget.cpp
line 559:  computeConstraintVector(*_currentState, parameters,constraints);
 and then in StaticOptimization.cpp:
target.setCurrentState should be called after line 345

**Comment by jenhicks** [comment] 2022-11-23 00:16
Closing given age; feel free to re-open if high priority.

**Closed by jenhicks** 2022-11-23 00:16 UTC
