### ISSUE TITLE
Could not find git for clone of BTK

### ISSUE THREAD

**Issue by rmndrs89** [opensim-org/opensim-core#2853] opened 2020-08-03 13:43 UTC
I was trying to follow the instructions [here](https://github.com/opensim-org/opensim-core#on-ubuntu-using-unix-makefiles) to install OpenSim on Linux Ubuntu 20.04.1 LTS. 

However, I get stuck when using the CMake GUI, and the following error is thrown:

> CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2421 (message):  
    error: could not find git for clone of BTK  
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:3236 (_ep_add_download_command)
  CMakeLists.txt:122 (ExternalProject_Add)
  CMakeLists.txt:144 (AddDependency)

This happens after selecting:
**Where is the source code:** /opt/opensim-core-4.1/dependencies
**Where to build the binaries:** /opt/opensim-core-dependencies-build
**Configure** > **Specify the generator for this project:** Unix Makefiles

Presumably, this has to do with BTK (could not find git for clone of BTK), but I have no idea on how to proceed. I was planning on superbuilding BTK later on. Any idea on how to move forward?

I am building on Ubuntu 20.04.1 LTS, 64-bit, GNOME 3.36.3

**Comment by aymanhab** [comment] 2020-08-03 15:39
This step should be automated for you since the CMake files specify the repo/commit for BTK. We default to not building any C3D support but continuous integration uses EZC3D. Unless you have personal preference to use BTK, and plan to read C3D files, you can choose to superbuild ezc3d instead (when building dependencies) and choose EZC3D when building opensim-core.

**Comment by chrisdembia** [comment] 2020-08-03 17:18
It seems that you have not installed `git`. Run `apt install git`.

**Comment by aymanhab** [comment] 2020-09-01 23:40
I believe this is not a bug but rather a configuration/machine specific issue. Closing but please let us know and reopen if you believe there's a bug here @rmndrs89

**Closed by aymanhab** 2020-09-01 23:40 UTC

**Comment by Francesca-Oppia** [comment] 2022-08-03 12:13
Hello! I have the same issue but it seems it can't find git for clone simbody neither ezc3d. I did install git on my PC but it didn't work. Can you help me please?
