### ISSUE TITLE
.mot and .sto files with NaNs are not plotted correctly

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#2505] opened 2019-06-20 21:03 UTC
If the file is selected in the plotter the data seems to be read in correctly:
`Storage: read data file =F:\Users\aseth\Downloads\NanExample\Running_GRF_cop_nans.mot (nr=2460 nc=28)`

But when plotted, only the subset prior to a NaN is plotted no matter what column the NaN appears in. For example, there are no NaN's in the forces (just in CoP) but only the time prior to the NaN in the CoP column is plotted.

![image](https://user-images.githubusercontent.com/6494122/59881321-28152d80-9364-11e9-980a-9b08721765d1.png)

**Comment by jenhicks** [comment] 2019-11-11 21:23
We are not able to reproduce, so closing. If you experience again @aseth1 please re-open and share the file. Thanks!

**Closed by jenhicks** 2019-11-11 21:23 UTC
