### ISSUE TITLE
Got stuck with double types in python

### ISSUE THREAD

**Issue by nikorose87** [opensim-org/opensim-core#1368] opened 2016-10-28 19:10 UTC
Hi 

I am trying to do the simple TugofWar exercise in python just for learning a bit more, Unfortunately,  I got stuck setting bounds on coordinates because the `setRange` asked for a double type. I have tried to change the type of the numbers with the next commands:
- c_double
- float
- ArrayDouble

but all of them didn't work, throwing the next error:

`TypeError: in method 'Coordinate_setRange', argument 2 of type 'double [2]'`

The part of the code is here in case it could be useful:

```

# set bounds on coordinates
#angleRange = osim.ArrayDouble.createVec3(-math.pi/2,math.pi/2,0)
# Creates a list containing 5 lists, each of 8 items, all set to 0
#w, h = 1, 2
#angleRange = [[0 for x in range(w)] for y in range(h)]
#positionRange = [[0 for x in range(w)] for y in range(h)]
#angleRange = (c_double(-math.pi/2),c_double(math.pi/2))
#angleRange[0][0] = c_double(-math.pi/2)
#angleRange[1][0] = c_double(math.pi/2)
#positionRange = (c_double(-1),c_double(1))
angleRange = osim.ArrayDouble(-math.pi/2)
angleRange.append(math.pi/2)
positionRange = osim.ArrayDouble(-math.pi/2)
print (angleRange,positionRange)
blockToGround.upd_coordinates(0).setRange(angleRange)
blockToGround.upd_coordinates(1).setRange(angleRange)
blockToGround.upd_coordinates(2).setRange(angleRange)
blockToGround.upd_coordinates(3).setRange(positionRange)
blockToGround.upd_coordinates(4).setRange(positionRange)
blockToGround.upd_coordinates(5).setRange(positionRange)

```

thanks!

**Comment by chrisdembia** [comment] 2016-10-28 19:17
Use `Coordinate::setRangeMin()` and `Coordinate::setRangeMax()`. Please close this issue if this works for you.

**Comment by nikorose87** [comment] 2016-10-28 19:36
Well Thanks

It works in this way:

```
blockToGround.upd_coordinates(0).setRangeMin(float(-math.pi/2))
blockToGround.upd_coordinates(0).setRangeMax(float(math.pi/2))
```

Thanks again!

**Comment by aymanhab** [comment] 2016-10-28 19:40
Chris, I'm ok with closing as long as we open an issue to address or remove
unusable methods from bindings if that's the case here.

Thanks
Ayman

**Comment by nikorose87** [comment] 2016-10-28 23:24
Dear Crhis

I am confused with the visualization process in python, I mean, In the example provided you use `Manager` to show the model, but the API says that this command couldn't be applied yet in python or Matlab due to since the SimTK::Integrators are not exposed in those languages . So, I tried with the command `run` command but it didn't show anything. I'm trying with TugOfWar model.

Thanks
Nikorose

**Comment by chrisdembia** [comment] 2016-10-28 23:26
The documentation says that the constructor that takes two arguments cannot be used in Python or MATLAB. The variant that takes just one argument *can* be used in Python/MATLAB; see [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Manager/Manager.h#L140).

**Comment by chrisdembia** [comment] 2016-10-28 23:27
What do you mean by the `run` command?

**Comment by nikorose87** [comment] 2016-10-28 23:34
According to the scripts of TugOfWar visualization I modified for python, as follows:

```
import opensim  as osim
osimModel = osim.Model('tug_of_war_muscles_controller.osim')
osimModel.setUseVisualizer(True) # Set up the visualizer to show the model and simulation
osimModel.initSystem() # Initializing the model

# Define some parameters for the simulations

tool = osim.ForwardTool() # Define the new tool object which will be run
tool.setModel(osimModel) # Define the model which the Forward simulation will operate on

# Define the start and finish times for simulation
tool.setStartTime(0)
tool.setFinalTime(3)
tool.setSolveForEquilibrium(True)

# Define the name of the forward analysis
tool.setName('tugOfWar')
#Run the simulation

tool.run()
```
But after being given the arguments of the simulation it throws the following error: 

> Integrating from 0 to 3
ForwardTool::run() caught exception 
SimTK Exception thrown at Integrator.cpp:431:
  Integrator initialization failed apparently because:
SimTK Exception thrown at SmallMatrixMixed.h:879:
  Error detected by Simbody method lapackInverse(Mat<>): Matrix is singular so can't be inverted (Lapack getrf info=1).
  (Required condition 'info==0' was not met.)

**Comment by chrisdembia** [comment] 2016-10-28 23:43
Well you *can* use the manager instead of the ForwardTool. The issue is likely due to an error in how the model is formulated. For example, make sure you do not have massless bodies at the end of the multibody tree.

**Comment by aymanhab** [comment] 2016-10-31 18:22
@chrisdembia The signature of the Coorindate.setRange method in python looks like     
``
def setRange(self, aRange):
        """
        setRange(Coordinate self, double [2] aRange)

        Parameters:
            aRange: double [2]

        """
        return _simulation.Coordinate_setRange(self, aRange)
``
While I can create double[] in Java, not sure how Python handles these raw arrays or pointers. The function is used in multiple test cases in C++.

**Comment by chrisdembia** [comment] 2016-10-31 18:24
Python does not allow raw arrays. In python, we would want the method to take a list:

```python
coord.setRange([-1, 1])
```

But I also think it is fine to exclude the method from the python bindings.

**Comment by jenhicks** [comment] 2016-11-03 18:27
@klshrinidhi will look for other instances.

**Closed** 2016-11-10 19:18 UTC
