### ISSUE TITLE
Problems with OpenSimConfig.cmake on Windows

### ISSUE THREAD

**Issue by sherm1** [opensim-org/opensim-core#738] opened 2016-01-19 05:31 UTC
I built and installed OpenSim 4.0 Debug on Windows and then tried to link a main program against it that used a CMake file constructed from the `SampleCMakeLists.txt` file, so it used `OpenSimConfig.cmake`. (This was Matt Millard's program from [this forum post](https://simtk.org/forums/viewtopic.php?f=91&t=6317#p16114).)
- First it failed in CMake because it claimed that _installdir_/**lib** didn't exist. That's because on Windows the lib directory is in `sdk/lib`. I hacked `OpenSimConfig.cmake` to add `sdk/` and then CMake succeeded.
- Then it failed because it tried to use the Simbody non-debug libraries. I couldn't see where the config targets file specifies to use debug libraries. They were definitely present in the OpenSim bin directory, and I was building Matt's main program in that same directory. I modified the Linker Properties setting in Visual Studio by hand to switch to the Simbody `_d` libraries, and then everything worked.

/cc @chrisdembia, @klshrinidhi

**Comment by chrisdembia** [comment] 2016-01-19 06:37
Thanks for reporting. I've heard similar reports before and have a few ideas for how to solve the second problem. Shrinidhi and I have discussed this and a large part of the problem is that we copy the simbody libraries.

**Comment by klshrinidhi** [comment] 2016-01-19 06:52
I haven't tried linking against OpenSim like this so far. I was assuming that `OpenSimConfig.cmake` would know that we copy dependencies. 

Maybe unrelated to this issue but on Windows, I think the executable built by linking against OpenSim libraries may require a copy of all its dependencies from OpenSim in its own directory. Otherwise, linker will not complain but at runtime, DLLs will not be found.

**Comment by chrisdembia** [comment] 2016-01-19 06:57
> Maybe unrelated to this issue but on Windows, I think the executable built by linking against OpenSim libraries may require a copy of all its dependencies from OpenSim in its own directory. Otherwise, linker will not complain but at runtime, DLLs will not be found.

That's a good point. I think this is their own problem, though, just like it's OpenSim's problem for its own dependencies. Such end users can decide whether to set PATH, copy the dlls, use manifest files, etc.

> I was assuming that OpenSimConfig.cmake would know that we copy dependencies.

It is supposed to be aware that we copy the libraries. Still the chance for bugs though :(

**Comment by aymanhab** [comment] 2017-03-16 18:41
This will be addressed by another issue #693

**Closed by aymanhab** 2017-03-16 18:41 UTC
Labels: Build
