### ISSUE TITLE
Inverse kinematics rotates segments, possibility to constrain leg rotation? 

### ISSUE THREAD

**Issue by DavidePetrella** [opensim-org/opensim-core#3360] opened 2023-01-17 09:12 UTC
During the inverse kinematics stage of our pipeline, during a bilateral drop excercise with bent knees, al lower leg segments rotate 180° causing large RMSE and no possible dynamic optimilization solution.

Is there a way to add constraint to the possible knee & hip angles to try and avoid this? Or what should be our best crouse of action?

Labbeling has been checked and everything seems to be correct.

We are using teh GAIT2392-model.

We also have an unilateral drop exercise which doesn't seem to have any issues.

Thank you in advance.
![Screenshot_20230117_101119](https://user-images.githubusercontent.com/119957393/212856927-e903ebe3-11ed-4e32-8ac8-05784caf26d6.png)

**Comment by aymanhab** [comment] 2023-01-17 18:13
We don't usually add constraints but rather limit the range for coordinates if we want to restrict the search spce for the inverse kinematics solver. Maybe the solver fellinto some local minimum and that will help. Since this is not a development/coding bug I'll close this issue. If you run into a clear bug please reopen and add more details to helpus reproduce. Thank you

**Closed by aymanhab** 2023-01-17 18:13 UTC
