### ISSUE TITLE
Writing TableVec3 to file

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1206] opened 2016-08-23 23:27 UTC
I am trying to write a tableVec3 to file. CSVFileAdapter and STOFileAdapter do not accept a Vec3 table. TRCFileAdapter (which accepts TableVec3) requires a data rate to write to a file — results from a forward simulation do not have a constant data rate, so I can't write using that. 

How would I print Vec3 results from a simulation?

**Comment by jimmyDunne** [comment] 2016-08-24 00:35
related to #1158

**Comment by chrisdembia** [comment] 2016-08-24 05:32
I think you have to wait for #1158 to be merged.

**Comment by jimmyDunne** [comment] 2016-09-12 22:45
#1158 didn't solve this issue for Matlab. How can you write a TableVec3 to file in through Matlab? @chrisdembia @aseth1

**Comment by aseth1** [comment] 2016-09-12 23:48
`STOFileAdapter` class is now `STOFileAdapter_<T>` and we had to wrap these as @klshrinidhi did with `Vec3`, `SpatialVec` and others [here](https://github.com/opensim-org/opensim-core/pull/1158/files#diff-1da5685f3b49fed3c5f31e74c90ecf30R175). Did you try using `STOFileAdapterVec3` or is it that which is not working?

**Comment by jimmyDunne** [comment] 2016-09-13 06:18
STOFileAdapterVec3 is working. I am able to print data to file now. Thanks.

**Comment by aymanhab** [comment] 2016-09-13 16:36
I'm reopening this because:
If STOFileAdapter is not usable then it shouldn't appear after wrapping at all. If it's implicitly assuming <double> then we should either document that or change the name when instantiating through SWIG so that it is less confusing to users. We should follow a consistent naming strategy across binding in SWIG and document that for future reference.

**Comment by aseth1** [comment] 2016-09-13 18:06
In Jave `STOFileAdapter` is wrap of  `STOFileAdapter_<double>` and `STOFileAdapterVec3`, `STOFileAdapterVec6`, ... (see above link) are also wraps of corresponding specializations. I believe this conforms to our "naming strategy". What is the specific issue/grievance for reopening this issue? Is it that `STOFileAdapter` cannot be used to load tables of arbitrary type?

**Comment by aymanhab** [comment] 2016-09-13 18:43
The issue is that we don't have a "naming strategy"! For example ArrayDouble is Array_double while  Vector is Vector_double. Using nothing to indicate Double in some cases, or 1 in another makes it harder to tell Matlab users how to translate C++ code/examples/Doxygen into Java/Matlab. There's a document on confluence that summarizes the current mapping as of version 3.3 and it's not kept up-to-date or a replacement provided. Check 
http://simtk-confluence.stanford.edu:8080/display/OpenSim/Common+Scripting+Commands

**Comment by tkuchida** [comment] 2016-09-13 18:58
If possible, I think it would be best to present Matlab users with methods of the form STOFileAdapter:cow: or STOFileAdapter_:cow:, where :cow: is always the type (double, Vec3, etc.). Otherwise, the user needs to remember :cow: = (type == double) ? null : type.

**Comment by aymanhab** [comment] 2016-09-13 19:01
:+1: :heart: :cow:

**Comment by aseth1** [comment] 2016-09-13 19:19
OK i see the bigger issue now, but I still don't think the discussion belongs in this issue.  Please create a new issue. I believe we agree that the issue of writing out a TimeSeriesTableVec3 was addressed.

**Comment by jimmyDunne** [comment] 2016-09-13 19:23
`STOFileAdapterVec3` or `STOFileAdapterVec6` don't appear in the doxygen or anywhere in the code base. Seeing `TimeSeriesTable_<SimTK::Vec3>` doesn't help a Python/Java user. Just a thought.

**Comment by aymanhab** [comment] 2016-09-13 19:25
Agreed, new issue created, this one can be closed.

**Closed by aymanhab** 2016-09-13 19:25 UTC
