### ISSUE TITLE
XSensDataReader not working with MT Manager 19.2 (last version) 

### ISSUE THREAD

**Issue by antoinefalisse** [opensim-org/opensim-core#2812] opened 2020-06-23 09:48 UTC
Hey,

When exporting data with the latest version of MT manager (19.2), the update rate is no longer reported in the output .txt files (it was the case with the previous version - MT manager 4.6). This causes problems when reading the data with the XSensDataReader (see [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/XsensDataReader.cpp#L61)). I have looked for options to export the update rate within MT manager but did not find anything.

Thanks,
Antoine

**Comment by aymanhab** [comment] 2020-06-26 20:42
Thanks for reporting @antoinefalisse, we worked with a specific data-file/formats that we had access to, if there's a new format that we can support, please feel free to attach/send documentation or describe here, or in a PR that builds on existing XSensDataReader class. Thank you

**Comment by antoinefalisse** [comment] 2020-06-29 11:13
Hey @aymanhab, here is an example of what I get out of the latest version of MT manager (19.2 - I assume the version new users will have when starting with Xsens):

[MT_01200454_000-000_00B40DE4.txt](https://github.com/opensim-org/opensim-core/files/4844982/MT_01200454_000-000_00B40DE4.txt)

As you can see, there is no information about the update rate anymore. Since [that rate is required by the XSensDataReader](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/XsensDataReader.cpp#L61), this causes problems when converting the data in this .txt file into the different <>.sto files.

**Comment by aymanhab** [comment] 2020-06-29 16:40
@antoinefalisse Thanks for looking into this, we can disable the check and assume a fixed DataRate if not specified (as is the case here) but what is this data rate then? Is it documented somewhere else either in files or in the XSens documentation? Also I remember user reporting that XSens being capable of exporting Quaternions directly, is that something we need to support? Thank you.

**Comment by antoinefalisse** [comment] 2020-06-30 07:57
@aymanhab I am not sure about the data rate. In the documentation of MTw Awinda (see attached document, table 1, p34), they recommend an update rate depending on the number of sensors being used. But based on what my colleagues told me, they can still choose between several update rates. For instance, we used 15 sensors so it was recommended to use 60Hz but I guess we could have picked 40Hz as well. Note that [this post](https://base.xsens.com/hc/en-us/community/posts/360008624120-MTw-Awinda-and-sample-time-) might be relevant as well. I did not find a way to extract the update rate in txt file such that we could then read it, annoying.

[MTw_Awinda_User_Manual.pdf](https://github.com/opensim-org/opensim-core/files/4850184/MTw_Awinda_User_Manual.pdf)

Regarding the quaternions, yes it is possible to export them directly with MT manager. A difference between those and the ones returned by Simbody is that Simbody returns canonical quaternions in which the first element is always positive. This is not the case with MT manager. But I guess it would be pretty easy to check if the first element is positive and if not invert the quaternions to make sure IK is fine downstream. I quickly checked the quaternions returned by MT manager and compared the values with those returned by Simbody from the rotation matrices and they seem to be similar.

**Comment by jenhicks** [comment] 2020-09-01 19:30
@aymanhab Is this still an open issue?

**Comment by aymanhab** [comment] 2020-09-01 20:28
Yes, it is since the format has changed.

**Comment by aymanhab** [comment] 2020-09-01 23:46
Hello @antoinefalisse, can you debug this out to size the scope of the change? Is this the latest version of the software? It appears the issue is a few more comment lines in the header. We can key off Firmware version to tell if time is included or not,  let me know what you find out if you get around to it. Thank you

**Comment by antoinefalisse** [comment] 2020-09-02 07:54
Hi @aymanhab I have downloaded the latest version of the software MT manager 2020.0 but I get the same as for the 2019.2 version I tried out before. So yes the issue is a few more comment lines in the header of the output txt files that include information about the Update Rate. I could not find a way to export the Update Rate in another way.

**Comment by aymanhab** [comment] 2020-09-03 18:57
Thanks @antoinefalisse can you look into a PR that beefs the test case to read a file on the new format? The case will fail but we'll have the data to test a fix/change. Thank you

**Comment by antoinefalisse** [comment] 2020-09-09 16:09
Hey @aymanhab that might be helpful to have the mtb files that were used to create the orientation files used for the test case. That way I could just reprocess them using the newer version of the software and replace the xisting orientation files. Do you have them somewhere?

**Comment by aymanhab** [comment] 2020-09-14 15:57
@antoinefalisse We decided early on not to include mtb files in our repo because these files are binary/proprietary format and since binary files can't be diffed so they don't belong. If you can include the exported .txt files/folder and a hypothetical test code that follows the same pattern as other xsens files we can get moving. Thank you

**Comment by antoinefalisse** [comment] 2020-09-15 05:34
Hi ayman thanks. I am on vacation for a couple of weeks so I will look into
that when I'm back.

Op ma 14 sep. 2020 17:58 schreef Ayman Habib <notifications@github.com>:

**Comment by antoinefalisse** [comment] 2020-10-20 00:54
@aymanhab sorry for the delay. I am back to work now. Do you still my input for this? If so, I can make some time this week.

**Comment by aymanhab** [comment] 2020-10-20 15:37
Welcome back @antoinefalisse Indeed if you can add short exported .txt file(s) on the latest format, that would be a good place to start supporting it in code and test case. Thank you

**Comment by antoinefalisse** [comment] 2020-10-20 23:32
Sure, here is an example .txt file exported using Xsens MT Manager 2020:
[test_file-000_00B40DE4.txt](https://github.com/opensim-org/opensim-core/files/5412205/test_file-000_00B40DE4.txt)

Let me know if you want me to help.

**Comment by aymanhab** [comment] 2021-01-08 18:29
I believe this has been addressed and merged.

**Closed** 2021-03-25 21:13 UTC
Labels: good first issue
