### ISSUE TITLE
Mesh objects don't show up, despite being found by findGeometryFile()

### ISSUE THREAD

**Issue by ThomasMiconi** [opensim-org/opensim-core#727] opened 2015-12-22 01:12 UTC
Hi all, thanks for the great software!

I have installed Opensim 4.0 from the GitHub repo, and it seems to work fine, including with visualization. 

My problem is that Mesh objects (read from vtp files) just don't show up on the API visualizer. I can add simple geometries like Sphere without problems, but if I try to use addMeshGeometry, or addGeometry with a Mesh object read from a file, the object doesn't show up on the screen (everything else runs fine).

This doesn't seem to be a problem of not finding the vtp file, because 1) I put the block.vtp file in the same directory as the program (and also in $OPENSIM_HOME/Geometry) and 2) findGeometryFile() finds it.

The worrying thing is that even in the ExampleMain [tug-of-war example] (https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Examples/ExampleMain/OutputReference/TugOfWar_Complete.cpp), the block defined by the mesh file 'block.vtp' doesn't show up on the visualizer: the "block" actually shows up as a sphere. I notice that there is a Sphere geometry added just after the addMeshGeometry call [(line 135)](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Examples/ExampleMain/OutputReference/TugOfWar_Complete.cpp#L138). This shows up, but if I comment it out, there's just empty space where the block should be. The fact that someone added a Sphere to "fill up" for the non-displaying mesh block suggests that there is a known issue with mesh files?

I have posted my very simple model-loading code at http://pastebin.com/LF8EJBKa .

Let me know if I'm doing something wrong. Thanks for any help!

**Comment by aseth1** [comment] 2016-03-26 00:00
I believe the problem is back. For the Luxo example the .obj files are found and appear to be added to the silo of decorations in `Geometry::generateDecorations` but somehow fail to draw. If I add a `Sphere` it displays fine.

**Comment by aseth1** [comment] 2016-03-29 18:21
@aymanhab any ideas why/how this bug came back?

**Comment by aymanhab** [comment] 2016-03-30 00:32
@aseth1 This bug is unlikely to be back as is. The issue here was miscommunication between the API and Visualizer where the former would create a SimTK::DecorativeMeshFile and the latter doesn't implement it. This was fixed on the simbody side and the latest visualizer implements DecorativeMeshFile as was seen/tested by everybody on the hackathon day. Possible issues that would cause the behavior you see: Using earlier version of Simbody, file exists but not readable or path/search issues (though these should through an exception). We can debug in your environment if none of these apply.

**Comment by aseth1** [comment] 2016-03-31 20:53
I was able to visualize the meshes during the lead up to the hackathon too both on my laptop and lab machine -that's why it was weird when it stopped displaying meshes. I updated to current master on laptop last night and you are right- visualized fine. I was up-to-date in the lab, but required a clean build to fix it here too. Sorry for the false alarm. I'll close it.

**Comment by aseth1** [comment] 2016-03-31 20:53
False alarm.

**Closed by aseth1** 2016-03-31 20:53 UTC
Labels: bug, DevWeek
