### ISSUE TITLE
AnalyzeTool Muscle Analysis Moment Flag

### ISSUE THREAD

**Issue by cclancy8** [opensim-org/opensim-core#3151] opened 2022-03-04 19:01 UTC
When requesting a MuscleAnalysis with the AnalyzeTool, the tool does not toggle the MuscleAnalysis to compute moments (and moment arms) even when `setComputeMoments(true)` is specified for the MuscleAnalysis. A check was done with   `getComputeMoments()`, which indicates that the option to compute moments was set to true. However, the printed .xml file of the AnalyzeTool does not have the flag indicated to compute moments and thus they are not calculated.

**Comment by aymanhab** [comment] 2022-03-04 19:27
My recollection is that this flag/property was not intended to be set explicitly but for internal use so that we know moment arms or moments are to be computed. This suggests that this shouldn't be exposed as a property as it would be confusing. The question from a user perspective is whether you can specify a list of Muscles and Coordinates and then ask for MomentArms or Moments

**Comment by cclancy8** [comment] 2022-03-09 21:39
Would it be possible to update the MuscleAnalysis so that moments and moment arms can be calculated with this flag? These result quantities are helpful in analysis. I can manually change the printed xml file to compute moments and moment arms with setting this flag to true, but I would like to have this an automated option when running for many different models.

**Comment by carmichaelong** [comment] 2022-03-10 06:03
@cclancy8 do you have a snippet of code / files to reproduce?

**Comment by carmichaelong** [comment] 2022-03-10 06:05
It looks like the flag that `setComputeMoments()` changes might actually be what should control that behavior: https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Analyses/MuscleAnalysis.cpp#L642

**Comment by cclancy8** [comment] 2022-03-10 06:23
Yes - I use `setComputeMoments(true) `. I also check with `getComputeMoments()` and get back true, but when I open the xml, the flag is unchanged. This is my code:

**Comment by carmichaelong** [comment] 2022-03-10 07:06
I'm guessing you only ever run this using the .xml file then, and not using the `myAnalyzeTool` object? I was able to reproduce your issue (i.e., the .xml file is incorrect), and then when I went to double check by peeking into the analyze tool object, it looks correct:
```
a = myAnalyzeTool.updAnalysisSet().adoptAndAppend(MA);
b = MuscleAnalysis.safeDownCast(a);
b.getComputeMoments()
```
This prints a 1 out too

**Comment by carmichaelong** [comment] 2022-03-10 21:28
If you've got `myAnalyzeTool` object all setup correctly, then in theory it should be as simple as `myAnalyzeTool.run();`. FYI, while that should work, it's still definitely a bug that the writing to file is incorrect and Ayman will look into that soon

**Comment by cclancy8** [comment] 2022-03-11 19:46
@carmichaelong , for some reason running the object itself gives me an error that a model has not been set even though I do set it. It looks like @aymanhab might be fixing this, though. Thank you!

**Comment by aymanhab** [comment] 2022-04-07 20:18
@cclancy8 Please let us know if this has been fixed in the latest development build. Thank you.

**Comment by cclancy8** [comment] 2022-04-08 18:30
@aymanhab  Thank you! With the development build from continuous-integration#2085 , the `compute_moments` flag of the muscle analysis can now be set to true as shown on the printed xml file. However, if I run the analysis tool object itself ( `myAnalyzeTool.run(); `), I still get an error. It is fine if I run from the printed xml file.

**Comment by mrrezaie** [comment] 2022-05-01 07:37
Hi, I intended to post this issue and found this. In both Python and MATLAB setting `setComputeMoments` to "true" doesn't take any action and I have to adjust it manually in the XML file.

**Closed** 2022-11-23 19:00 UTC
