### ISSUE TITLE
Interference with ezc3d library

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3066] opened 2021-08-20 07:03 UTC
Hi,

I was using ezc3d in python without any problem. I got ImportError after installing OpenSim 4.2. I see that there is a file named ezc3d.dll in `OpenSim 4.2\bin` folder. After renaming this file, Python imports ezc3d properly.

Would be great if you would rename this file in your new release to prevent library interference (e.g. osimEzc3d.dll). 

Regards,
Mohammadreza

**Comment by mrrezaie** [comment] 2021-08-22 09:28
Dear Experts,

I renamed the `ezc3d.dll` file in the `OpenSim 4.2\bin` to keep using this library in Python. But I get the following error when I open the OpenSim:

![image](https://user-images.githubusercontent.com/38867713/130349889-9c4eb0f0-3bb9-4ff8-b308-e10b4d2db8fd.png)

It seems that OpenSim GUI doesn't work without this file. Any idea for this issue? I would like to use both OpenSim and ezc3d independently.

I'm looking forward to hearing from you.

Best,
Mohammadreza

**Comment by aymanhab** [comment] 2021-08-22 16:55
Modifying or renaming dlls within the OpenSim distribution is very likely to break the functionality and must be avoided. 

If for some reason you can't use the version of ezc3d included with OpenSim then you could either take turns using ezc3d and OpenSim, switching paths, or consult with ezc3d developers to see if the functionality is available through different API in OpenSim. If building from source and not planning to use ezc3d through OpenSim, then you can choose BTK or None for C3D support and then use your local build rather than an official distribution. Finally version 4.3 of OpenSim is available in Beta and has an upgraded ezc3d embedded into it. Since this is not a bug but a special issue with you trying to have two different versions of a library co-exist, I'll close this issue as not a development issue/bug.

**Closed by aymanhab** 2021-08-22 16:55 UTC
