### ISSUE TITLE
Update Scripting Documentation on Confluence

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2252] opened 2018-08-10 22:42 UTC
https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting

Update this page and its children to reflect API changes for 4.0

**Comment by chrisdembia** [comment] 2018-08-21 21:20
@carmichaelong and I went through the scripting pages:

1. The base "Scripting" page could give more specific examples to help users understand what they can and cannot do in scripting.
2. Update the scripting interfaces via which the commands are available (Python could be listed in more places).
3. Update doxygen links to point to user doxygen instead of developer doxygen?
4. Test all code snippets to see if they still work.
  1. Does "replaceMarkerSet()" still work?
5. Add some python code snippets (different from Matlab examples but share headings; e.g. "Creating an actuator" in Python and Matlab).

**Comment by jenhicks** [comment] 2018-08-21 21:24
Thanks @chrisdembia and @carmichaelong 

These all sound like good updates. 

Re item 3: It's up to you guys. Have the two versions diverged much? Do you think they will in the future?

**Comment by chrisdembia** [comment] 2018-08-21 21:53
@jenhicks we've updated the list.

**Comment by chrisdembia** [comment] 2018-08-21 21:54
> Have the two versions diverged much? Do you think they will in the future?

Depending on the page they can be very different. The user doxygen isn't cluttered with stuff about protected methods, etc.

We don't currently post user doxygen online, so perhaps we just stick with linking to the developer doxygen for now.

**Comment by jenhicks** [comment] 2018-08-21 21:59
Thanks for the updates.

Regarding 14, a tag seems more sustainable. Should we point people to the API guide in a 4.0 tag as well?

**Comment by chrisdembia** [comment] 2018-08-21 22:00
> Regarding 14, a tag seems more sustainable. Should we point people to the API guide in a 4.0 tag as well?

Yes I think so. The issue is that the tag doesn't exist yet. We can provide the correct links but they won't work until the tag is created.

**Comment by chrisdembia** [comment] 2018-08-23 20:59
@aymanhab do you have suggestions for how we can regenerate the following javadoc pages?

1. https://simtk.org/api_docs/opensim/gui_docs/org/opensim/console/OpenSimPlotter.html
2. https://simtk.org/api_docs/opensim/gui_docs/org/opensim/console/gui.html

**Comment by aymanhab** [comment] 2018-08-23 21:16
@chrisdembia you can create javadoc for a specific package inside NetBeans, I may have done that in the past. The problem is the crosslinks to classes not in the org.opensim.console package. Looking at the links above it looks like this is what I've done and then copied the specific html pages that are of interest.

**Comment by chrisdembia** [comment] 2018-08-27 17:36
@jenhicks I've attached a ZIP containing updated OpenSimPlotter.html and gui.html files. Can you upload these to https://simtk.org/api_docs/opensim/gui_docs/org/opensim/console/?


[Archive.zip](https://github.com/opensim-org/opensim-core/files/2324947/Archive.zip)

**Comment by chrisdembia** [comment] 2018-08-27 19:00
@aymanhab if we add a marker to `getCurrentModel()` in the scripting shell, it does not appear in the Navigator, even after calling `initSystem()`. Is this behavior expected?

**Comment by aymanhab** [comment] 2018-08-27 19:13
As discussed, there's no call to recreate/refresh the tree, so this is not surprising from development standpoint but may surprise users indeed. You may want to open an issue so that we can force recreating the GUI data-model (navigator, topology etc.)

**Comment by chrisdembia** [comment] 2018-08-30 17:50
@jimmyDunne it would be great if you could make a quick pass to review the changes that @carmichaelong and I made to this section. Is there anything else we should add or update?

**Comment by chrisdembia** [comment] 2018-08-31 17:43
Now that the GUI scripts are merged, I updated the list of GUI scripts on Confluence.

**Comment by chrisdembia** [comment] 2018-09-04 23:47
I've emailed Henry about updating the javadoc HTML.

**Comment by chrisdembia** [comment] 2018-09-05 00:10
The javadoc has been updated; I've checked off this task above.

**Comment by chrisdembia** [comment] 2018-09-05 00:38
Moving to Needs Verifying.

**Comment by jenhicks** [comment] 2018-09-06 16:10
Looks great!

A few comments:
- In the section on templatized classes there is a link that says it is updated as of 3.2
- Are the listed scripts included consistent with the ones that we've ultimately included in the distribution?

**Comment by chrisdembia** [comment] 2018-09-06 22:00
> In the section on templatized classes there is a link that says it is updated as of 3.2

I just updated this list.

> Are the listed scripts included consistent with the ones that we've ultimately included in the distribution?

Yes; @carmichaelong and I checked these lists.

Ready for verifying again. (link for convenience: https://simtk-confluence.stanford.edu:8443/display/OpenSim/Common+Scripting+Commands)

**Comment by jenhicks** [comment] 2018-09-07 21:10
Thanks. Looks good! I moved this to Verified.

**Closed** 2018-09-14 22:03 UTC
Labels: Documentation
