### ISSUE TITLE
Using a State from a StateTrajectory crashes on realizeDynamics call

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#1455] opened 2016-12-16 00:57 UTC
Worked some with @aseth1 on this using MATLAB. If you get a State from a StateTrajectory and call `Model::realizeDynamics(state)`, a crash occurs with the top of the stack showing `SimTK::GeneralForceSubsystem::adoptForce`. If muscles set `appliesForce` to `false`, then no error occurs (and states can be looped to see the model move over multiple frames with the visualizer).

**Comment by tkuchida** [comment] 2016-12-16 06:16
Attempted to reproduce with a MWE, but the following script did not crash. What's missing?

```
function runtest()

import org.opensim.modeling.*

model = Model('arm26.osim');
state = model.initSystem();
traj  = StatesTrajectory();

fprintf('Appending to StatesTrajectory...\n');
for i = 1:5
    state.setTime(i);
    model.getJointSet().get(1).getCoordinate().setValue(state, i/10);
    model.equilibrateMuscles(state);
    traj.append(state);
    showState(state);
end

fprintf('Recalling from StatesTrajectory...\n');
for i = 0:traj.getSize()-1
    trajElem = traj.get(i);
    model.realizeDynamics(trajElem);
    showState(trajElem);
end

%%%%%%%%%%%%%%%%%%%%
function showState(state)
fprintf('[');
for i = 1:state.getNY()
    fprintf('%0.6f', state.getY().get(i-1));
    if (i < state.getNY()), fprintf(', '); end
end
fprintf(']\n');
```

**Comment by aseth1** [comment] 2016-12-16 06:29
thanks for investigating @tkuchida and for the nice test script. I am also not seeing the issue if I simulate the tug of war model to generate a `StatesTrajectory`. I think the main difference is that @carmichaelong is creating a `StatesTrajectory` from a Storage file (I believe it is a previous CMC solution). Secondarily, he is using the gait2354 model.

**Comment by tkuchida** [comment] 2016-12-16 07:25
Thanks for clarifying. I'm also crashing (segfault) on `model.realizeDynamics(trajElem);` with arm26, but only when the StatesTrajectory was constructed via `StatesTrajectory::createFromStatesStorage()`. Same issue with the analogous code in C++, which rules out a wrapping issue.

The doxygen for `StatesTrajectory::createFromStatesStorage()` indicates that "The resulting StatesTrajectory will restore continuous state variable values, but not discrete state variable values, modeling option values, etc.", so the issue appears to be that `Model::realizeDynamics()` is looking for a piece of the State that isn't there (and is causing an access violation :boom: when attempting to fetch it).

**Comment by tkuchida** [comment] 2016-12-16 07:48
A workaround is to use (hijack) the State returned by `initSystem()`:
```
trajElem = traj.get(i);
state.setY(trajElem.getY());
```
though I think that defeats the intended purpose of StatesTrajectory.

**Comment by chrisdembia** [comment] 2016-12-16 17:41
Thanks for reporting. The implementation of `createFromStatesStorage()` uses the state returned by `initSystem()` as the basis for every state in the trajectory.

**Comment by chrisdembia** [comment] 2016-12-16 19:45
Have any of you already started trying to work on a fix? If not, I can try to fix this.

**Comment by tkuchida** [comment] 2016-12-16 20:50
> Have any of you already started trying to work on a fix?

Not me, but feel free to assign me if you like.

**Comment by carmichaelong** [comment] 2016-12-16 22:35
I have not started on a fix either, but let me know if I can help in any way.

**Comment by chrisdembia** [comment] 2016-12-17 05:14
I'll give this a shot. Thanks for your willingness to help @tkuchida @carmichaelong. 

The error seems to result from using a state object on a different model than the one it was generated with. The following snippet also reproduces the issue (without using the StatesTrajectory):

```cpp
    Model model("gait2354_simbody.osim");
    model.initSystem(); // 1
    std::vector<State> states;
    {
        Model copy(model);
        states.push_back(copy.initSystem());
    }
    //model.initSystem(); // 2
    model.realizeDynamics(states[0]);
```

The error happens whether `initSystem()` is in location 1 **or** 2.

The `createFromStatesStorage()` function is indeed doing the above (using an internal copy of the model to create the states that are then returned to the user.

**Comment by chrisdembia** [comment] 2016-12-19 05:22
I figured out what's going wrong. I had assumed that the State object is independent from any given instance of the same exact System. This assumption is wrong: the State contains a cache entry holding onto `Force*`s that are in the System (see [here](https://github.com/simbody/simbody/blob/master/Simbody/src/GeneralForceSubsystem.cpp#L643) and [here](
https://github.com/simbody/simbody/blob/master/Simbody/src/GeneralForceSubsystem.cpp#L713)). After the scope holding `copy` closes, `copy`'s Forces are deleted, but `states[0]` still holds a cache entry that points to the Forces that were in `copy` (and that are now deleted).

Right now, `createFromStatesStorage()` was made so that the user does *not* need to call `initSystem()` before calling `createFromStatesStorage()`. Internally, `createfromStatesStorage()` makes a copy of the passed-in model and calls `initSystem()` on it. 

One fix is to (i) require users to have called `initSystem()` before calling `createFromStatesStorage()` (I want to maintain that `createFromStatesStorage()` takes a const reference to the model) and (ii) no longer make a copy of the model within `createFromStatesStorage()`.

Another fix is to call `state.invalidateAllCacheAtOrAbove(SimTK::Stage::Instance);` within `createFromStatesStorage()`, after calling `initSystem()`. This erases the `Force*`s from the cache.

**Comment by tkuchida** [comment] 2016-12-19 19:43
Nice sleuthing 🔍

> One fix is to (i) require users to have called `initSystem()` before calling `createFromStatesStorage()` (I want to maintain that `createFromStatesStorage()` takes a const reference to the model) and (ii) no longer make a copy of the model within `createFromStatesStorage()`.

I like this fix: there will be a clear "initSystem() must be called first!" exception, and any issues with the model will be caught/handled by `initSystem()` before `createFromStatesStorage()` is called (i.e., `createFromStatesStorage()` has a clear precondition).

**Comment by jenhicks** [comment] 2017-01-05 19:32
@chrisdembia Are you working on a fix for this? Let us know if you need help.

**Comment by chrisdembia** [comment] 2017-01-06 19:07
I have not worked on this yet. The fix should be fairly straightforward, but I need to know what others think the correct fix is (of the two I gave above).

**Comment by jenhicks** [comment] 2017-01-12 19:19
Consensus is to do both.

**Closed** 2017-01-23 05:25 UTC
Labels: bug
