### ISSUE TITLE
Moco Solver: OpenSim::MocoSolution OpenSim::MocoTrack::solve()': casVector should be 1-dimensional, but has size 0 x 0

### ISSUE THREAD

**Issue by mkirby42** [opensim-org/opensim-core#3085] opened 2021-09-24 20:58 UTC
Using all the code provided in the [example](https://simtk.org/api_docs/opensim/api_docs/exampleMocoTrack_8py-example.html)

Running in [latest docker container](https://hub.docker.com/r/stanfordnmbl/opensim-python/tags?page=1&ordering=last_updated)

Data files provided in the [examples](https://github.com/opensim-org/opensim-core/tree/master/OpenSim/Examples/Moco/example3DWalking)

Code
```
import os
import opensim as osim

def torqueDrivenMarkerTracking():
    
    track = osim.MocoTrack()
    track.setName("torque_driven_marker_tracking")

    modelProcessor = osim.ModelProcessor("/root/opensim_install/share/doc/OpenSim/Code/Python/Moco/example3DWalking/subject_walk_armless.osim")
    modelProcessor.append(osim.ModOpAddExternalLoads("/root/opensim_install/share/doc/OpenSim/Code/Python/Moco/example3DWalking/grf_walk.xml"))
    modelProcessor.append(osim.ModOpRemoveMuscles())
    modelProcessor.append(osim.ModOpAddReserves(250))
    track.setModel(modelProcessor)

    track.setMarkersReferenceFromTRC("/root/opensim_install/share/doc/OpenSim/Code/Python/Moco/example3DWalking/marker_trajectories.trc")

    track.set_allow_unused_references(True)

    track.set_markers_global_tracking_weight(10)

    markerWeights = osim.MocoWeightSet()
    markerWeights.cloneAndAppend(osim.MocoWeight("R.ASIS", 20))
    markerWeights.cloneAndAppend(osim.MocoWeight("L.ASIS", 20))
    markerWeights.cloneAndAppend(osim.MocoWeight("R.PSIS", 20))
    markerWeights.cloneAndAppend(osim.MocoWeight("L.PSIS", 20))
    markerWeights.cloneAndAppend(osim.MocoWeight("R.Knee", 10))
    markerWeights.cloneAndAppend(osim.MocoWeight("L.Knee", 10))
    markerWeights.cloneAndAppend(osim.MocoWeight("R.Ankle", 10))
    markerWeights.cloneAndAppend(osim.MocoWeight("L.Ankle", 10))
    markerWeights.cloneAndAppend(osim.MocoWeight("R.Heel", 10))
    markerWeights.cloneAndAppend(osim.MocoWeight("L.Heel", 10))
    markerWeights.cloneAndAppend(osim.MocoWeight("R.MT5", 5))
    markerWeights.cloneAndAppend(osim.MocoWeight("L.MT5", 5))
    markerWeights.cloneAndAppend(osim.MocoWeight("R.Toe", 2))
    markerWeights.cloneAndAppend(osim.MocoWeight("L.Toe", 2))
    track.set_markers_weight_set(markerWeights)

    track.set_initial_time(0.81)
    track.set_final_time(1.65)
    track.set_mesh_interval(0.05)

    return track.solve()
```

```
RuntimeError: std::exception in 'OpenSim::MocoSolution OpenSim::MocoTrack::solve()': casVector should be 1-dimensional, but has size 0 x 0.
	Thrown at MocoCasOCProblem.h:108 in convertToSimTKVector().
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_13953/4183041812.py in <module>
----> 1 torqueDrivenMarkerTracking()

/tmp/ipykernel_13953/877474632.py in torqueDrivenMarkerTracking()
     40     track.set_mesh_interval(0.05)
     41 
---> 42     return track.solve()

~/opensim_install/lib/python3.8/site-packages/opensim/moco.py in solve(self)
   5278 
   5279     def solve(self) -> "OpenSim::MocoSolution":
-> 5280         return _moco.MocoTrack_solve(self)
   5281 
   5282     def solveAndVisualize(self) -> "OpenSim::MocoSolution":

RuntimeError: std::exception in 'OpenSim::MocoSolution OpenSim::MocoTrack::solve()': casVector should be 1-dimensional, but has size 0 x 0.
	Thrown at MocoCasOCProblem.h:108 in convertToSimTKVector().
```

**Comment by mkirby42** [comment] 2021-09-30 18:03
Getting this for any examples using Moco track

```
root@ea861416502b:/opensim-core/Bindings/Python/examples/Moco# python3.8 exampleSlidingMass.py
[info] ========================================================================
[info] MocoCasADiSolver starting.
[info] Thu Sep 30 17:58:44 2021
[info] ------------------------------------------------------------------------
Costs: (total: 1)
  goal. MocoFinalTimeGoal, enabled: true, mode: cost, weight: 1.0
Endpoint constraints: none
Kinematic constraints: none
Path constraints: none
States: (total: 2)
  /slider/position/speed. bounds: [-50, 50] initial: 0 final: 0
  /slider/position/value. bounds: [-5, 5] initial: 0 final: 1
Controls: (total: 1)
  /actuator. bounds: [-50, 50]
Parameters: none
[info] Number of threads: 2
[info] Set log level to Info.
[info] Set log level to Info.
Traceback (most recent call last):
  File "exampleSlidingMass.py", line 87, in <module>
    solution = study.solve()
  File "/root/opensim_install/lib/python3.8/site-packages/opensim/moco.py", line 4642, in solve
    return _moco.MocoStudy_solve(self)
RuntimeError: std::exception in 'OpenSim::MocoSolution OpenSim::MocoStudy::solve() const': casVector should be 1-dimensional, but has size 0 x 0.
	Thrown at MocoCasOCProblem.h:108 in convertToSimTKVector().
```

**Comment by mkirby42** [comment] 2021-09-30 18:57
The examples work when using the conda env from [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/ISB+Technical+Group+on+Computer+Simulation+%28TGCS%29+2021+OpenSim+Moco+Workshop)

When running
`opensim.moco.GetMocoVersionAndDate()`
I get `'version 4.3--, build date 05:13:50 Aug 19 2021'` in the docker container
and `'version 4.3-2021-08-27-4bc7ad9, build date 09:13:36 Aug 28 2021'` in the conda env

**Comment by fl0fischer** [comment] 2021-10-01 06:37
It seems that there is something wrong with the `liptropter.so` file in the opensim installation directory. For me, copying `liptropter.so` from the opensim build directory to the lib folder within installation directory solved this issue.

Duplicate of #3006

**Comment by mkirby42** [comment] 2021-10-01 13:19
We're using the default Casadi solver. The issue seems to be a problem with the initial guess outputting an empty vector for the time duration of the problem. I wouldn't think the Tropter solver would be involved.

**Comment by fl0fischer** [comment] 2021-10-01 17:14
I also did not expect the tropter solver to be involved, but replacing the libtropter.so file was the only way to get the Moco Python Examples running. However, I indeed could not identify what is the difference between both files. Very strange issue...

**Comment by nickbianco** [comment] 2021-10-01 19:08
Hi @mkirby42, thanks for providing more details on this issue. I'm not really sure why the Docker container fails, given that the examples work when installing OpenSim from the instructions for the TGCS workshop. Those instructions link to the latest version of OpenSim, and the Docker container includes a recent version of OpenSim as well. I don't think there's any differences between those versions that would cause this issue, so I think something funny is happening in the Docker container.

**Comment by fl0fischer** [comment] 2021-10-04 17:21
I think the problem is that OpenSim 4.3 is built with ipopt 3.12.8 as dependency (which provides libipopt.so.1.10.8), but the docker image only provides libipopt.so.1.9.9. Since "make install" removes the runtime path from libtropter.so, the installed version makes use of system-wide installed libraries (in the docker image, it uses /usr/lib/libipopt.so.1.9.9). This problem also occurs for manual linux builds of OpenSim 4.3 (apt, e.g., only supports ipopt 3.11.9, which also provides libipopt.so.1.9.9).

To circumvent this issue in the docker image, it suffices to replace the system ipopt library with the one used to build OpenSim:
`cp /opensim_dependencies_install/ipopt/lib/*.so* /usr/lib
`

For manual builds this should also work, or one could replace the libtropter.so from $OPENSIM_INSTALL_DIR/lib with the libtropter.so from $OPENSIM_BUILD_DIR, which still depends on the libraries from opensim_dependencies_install.

A fix for this issue would probably require to adjust the ipopt dependencies here: [https://github.com/opensim-org/opensim-core/blob/master/Vendors/tropter/tropter/CMakeLists.txt#L93]?

**Comment by nickbianco** [comment] 2021-10-05 21:54
> The issue seems to be a problem with the initial guess outputting an empty vector for the time duration of the problem.

@mkirby42 just to verify this, have you tried specifying your own initial guess as a workaround? You can use `guess = solver.createGuess()` to create a guess that is compatible with the problem and then specify this guess using `solver.setGuess(guess)` (optionally, you can make changes to the guess values before this step). The issue might be related to how MocoTrack handles initial guesses (since it manages it's own internal MocoStudy). Still not sure why this only happens in the Docker container, but this could narrow things down.

@fl0fischer are you seeing this same casVector zero-dimension issue, or is this a different issue related to the Docker container. The tropter/ipopt library issues seem off-topic from this thread. If so, please open a separate issue.

**Comment by fl0fischer** [comment] 2021-10-19 21:04
It was basically trial and error, once I've noticed that the issue is related to the libraries in the opensim install dir, I removed each library separately and found out that the error just appears when the new libtropter.so file is created and used (executing the building tests with install dir already included in the LD_LIBRARY_PATH helped to figure this out).

I would suggest to replace the [CMakeLists.txt](https://github.com/opensim-org/opensim-core/blob/524cb877dcea6d67ce7e68ad994792623c80663a/Vendors/tropter/cmake/CMakeLists.txt) with [this file](https://github.com/opensim-org/opensim-core/files/7376599/CMakeLists.txt), which copies all relevant libraries from ipopt and adol-c to the opensim installation dir. I built the latest OpenSim version from this git on a Ubuntu 20.04 system using this patched CMakeLists.txt and everything seems to work fine. 

In the docker image, replacing the `/usr/lib/libipopt.so*` files with `libipopt.so.1.10.8` from the dependencies dir also works fine:

`cp /opensim_dependencies_install/ipopt/lib/lib* /opensim_install/lib/`

**Comment by nickbianco** [comment] 2021-11-04 00:41
@aymanhab here is the issue I was referring to yesterday. If this is something you are able to test on your Ubuntu build, let me know.

**Comment by nickbianco** [comment] 2022-07-27 22:44
@aymanhab pinging you here again per our dev meeting conversation.

**Comment by aymanhab** [comment] 2022-07-27 23:54
I'll make  fresh Ubuntu 18 build to try and will let you know

**Comment by jenhicks** [comment] 2022-11-23 20:34
@nickbianco Can we close this one?

**Comment by nickbianco** [comment] 2022-12-05 19:15
@aymanhab did you ever get to try this on your Ubuntu build?

**Comment by GraceEMc** [comment] 2023-02-08 21:19
Hi there, I just wanted to follow up as I have been having a similar issue. I am running my own simulations on my Windows desktop and when I try to repeat the simulation on a Linux HPC, I get the casVector error midway through.

In my code I am using guess = solver.createGuess() as suggested and I can run the exampleMocoTrack script without issues. My desktop is running OpenSim 4.4-2022-06-11-bfc372a and version 4.4 is on the HPC if that could be a difference. Are there any potential fixes for this? Thanks

**Comment by nickbianco** [comment] 2024-04-09 20:50
@aymanhab, I'm looking to close out this issue. I think it was resolved via #3092 a while ago.

@GraceEMc, does this issue still persist for you on the latest versions of OpenSim?

**Comment by aymanhab** [comment] 2024-04-09 20:53
Unless @GraceEMc reports otherwise and can reproduce I'd agree to close .

**Comment by nickbianco** [comment] 2024-04-09 21:48
Hey @fl0fischer, we're looking to close out this issue since it seems to have been resolved some time ago. Let us know if more recent versions of OpenSim (e.g., 4.5) work as expected in your Docker containers or if you still need to copy libraries manually.

**Comment by GraceEMc** [comment] 2024-04-10 06:13
I haven't had any issues with v4.5. Thanks!

**Comment by nickbianco** [comment] 2024-04-10 17:13
Thanks @GraceEMc! I'll go ahead and close this then.

**Closed by nickbianco** 2024-04-10 17:13 UTC
Labels: Moco
