### ISSUE TITLE
Model fails to load: bouncing_block.osim

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1856] opened 2017-08-03 15:51 UTC
@tkuchida commented on [Thu Mar 02 2017](https://github.com/opensim-org/opensim-gui/issues/68)

**Platform:** Win 7 Pro 64-bit
**Version:** opensimWin64Alpha01.zip
**OPENSIM_HOME environment variable:** Points to 3.3 directory

**Error message**
![err1](https://cloud.githubusercontent.com/assets/4203505/23527487/fd13bb74-ff4a-11e6-8827-a93955b360d3.png)

**"Messages" window**
<pre>
Updating Model file from 20303 to latest format...
Visualizer couldn't read c:\Users\tkuchida\GitHub - GUI 4.0 alpha01\opensim\Geometry\big_block_centered.vtp because:
SimTK Exception thrown at PolygonalMesh.cpp:411:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Attempt to load a VTK PolyData (.vtp) file from file name 'c:\Users\tkuchida\GitHub - GUI 4.0 alpha01\opensim\Geometry\big_block_centered.vtp' failed with message:
  SimTK Exception thrown at PolygonalMesh.cpp:340:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Only format="ascii" is supported for .vtp file DataArray elements, got format="appended" for Points DataArray.
  (Required condition 'pointData.getRequiredAttributeValue("format") == "ascii"' was not met.)

  (Required condition '!"failed"' was not met.)

Visualizer couldn't read c:\Users\tkuchida\GitHub - GUI 4.0 alpha01\opensim\Geometry\linkage1.vtp because:
SimTK Exception thrown at PolygonalMesh.cpp:411:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Attempt to load a VTK PolyData (.vtp) file from file name 'c:\Users\tkuchida\GitHub - GUI 4.0 alpha01\opensim\Geometry\linkage1.vtp' failed with message:
  SimTK Exception thrown at PolygonalMesh.cpp:340:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Only format="ascii" is supported for .vtp file DataArray elements, got format="appended" for Points DataArray.
  (Required condition 'pointData.getRequiredAttributeValue("format") == "ascii"' was not met.)

  (Required condition '!"failed"' was not met.)

Visualizer couldn't read c:\Users\tkuchida\GitHub - GUI 4.0 alpha01\opensim\Geometry\linkage1.vtp because:
SimTK Exception thrown at PolygonalMesh.cpp:411:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Attempt to load a VTK PolyData (.vtp) file from file name 'c:\Users\tkuchida\GitHub - GUI 4.0 alpha01\opensim\Geometry\linkage1.vtp' failed with message:
  SimTK Exception thrown at PolygonalMesh.cpp:340:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Only format="ascii" is supported for .vtp file DataArray elements, got format="appended" for Points DataArray.
  (Required condition 'pointData.getRequiredAttributeValue("format") == "ascii"' was not met.)

  (Required condition '!"failed"' was not met.)

Loaded model toy_with_forces from file C:\Users\tkuchida\GitHub - GUI 4.0 alpha01\opensim\models\BouncingBlock\bouncing_block.osim
</pre>

---

@aymanhab commented on [Sun Mar 05 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-284275557)

Check if it opens on master, if yes then likely this has been fixed in core, will test after upgrading if not then open an issue for opensim-core. Thanks @tkuchida 

---

@tkuchida commented on [Mon Mar 06 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-284504560)

The following works on master:
```cpp
auto Model = model("bouncing_block.osim");
model.finalizeFromProperties(); //throws exception if this line is omitted
model.printSubcomponentInfo();
```

---

@aymanhab commented on [Mon Mar 06 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-284506261)

The GUI workflow invokes initSystem (which implicitly calls finalizeFromProperties), the change to require the new call finalizeFromProperties was not in the alpha code base, so I'd expect the issue to go away with upgrading API. Would be great though to try opening other models from the GUI-alpha distribution using master so that any necessary fixes are incorporated into the API core beta. Thanks much @tkuchida for investigating 🥇 

---

@tkuchida commented on [Mon Mar 06 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-284558784)

All models in `opensimWin64Alpha01\opensim\models\*.osim /s` load successfully in the API on master.

**Test code**
```cpp
auto model = Model(filename);
model.finalizeFromProperties();
model.printSubcomponentInfo();
```

**Model files tested**
Arm26/arm26.osim
BouncingBlock/bouncing_block.osim
BouncingBlock/bouncing_block_weak_spring.osim
DynamicWalker/WalkerModel.osim
DynamicWalker/WalkerModelAddCustomFeet.osim
DynamicWalker/WalkerModelTerrain.osim
DynamicWalker/WalkerModelTerrainAddCustomFeet.osim
Gait10dof18musc/gait10dof18musc.osim
Gait10dof18musc/subject01.osim
Gait10dof18musc/subject01_metabolics.osim
Gait10dof18musc/subject01_metabolics_path_actuator.osim
Gait10dof18musc/subject01_metabolics_path_spring.osim
Gait10dof18musc/subject01_metabolics_spring.osim
Gait2354_Simbody/gait2354_simbody.osim
Gait2354_Simbody/gait2354_with_pat_lig.osim
Gait2354_Simbody/subject01_simbody.osim
Gait2354_Simbody_Patellae/gait2354_simbody_patellae.osim
Gait2392_Simbody/gait2392.osim
Gait2392_Simbody/gait2392_simbody.osim
Gait2392_Simbody/subject01.osim
Gait2392_Simbody/subject01_adjusted.osim
Gait2392_Simbody/subject01_simbody_adjusted.osim
Jumper/DynamicJumperModel.osim
Leg6Dof9Musc/leg6dof9musc.osim
Pendulum/double_pendulum.osim
SoccerKick/SoccerKickingModel.osim
ToyLanding/ToyLandingModel.osim
ToyLanding/ToyLandingModel_activeAFO.osim
ToyLanding/ToyLandingModel_AFO.osim
Tug_of_War/Tug_of_War.osim
Tug_of_War/Tug_of_War_Millard.osim

---

@aymanhab commented on [Mon Mar 06 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-284559457)

Awesome, excellent job @tkuchida  👍 

---

@jenhicks commented on [Tue Mar 07 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-284840991)

Moved to "needs verifying" list for testing in the next GUI build

---

@aymanhab commented on [Mon Apr 03 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-291221554)

Trying to load the model now gives the error dialog 
![capture68](https://cloud.githubusercontent.com/assets/3972208/24622972/be37d118-185b-11e7-912f-5b86f17b28f3.JPG)
This obviously is the latest API Beta since Sockets mentioned in message didn't exist in previous versions
model in opensim-models/Models/BouncingBlock/bouncing_block.osim

---

@jenhicks commented on [Tue Apr 04 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-291646085)

@aseth1 

---

@tkuchida commented on [Tue Jun 06 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-306589944)

Still unable to open bouncing_block.osim with opensim_devWin64_060217.zip (same dialog box as @aymanhab noted on Apr 3 post, above).

---

@tkuchida commented on [Mon Jul 10 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-314321363)

Tested again using opensim_win64_070517_2.zip on Windows 7. Error message is identical to what Ayman posted above (Apr 3). Contents of Messages window:
<pre>
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
Updating Model file from 20303 to latest format...
Loaded model toy_with_forces from file C:\Users\tkuchida\GitHub - GUI 4.0 alpha04\opensim\Models\BouncingBlock\bouncing_block.osim
</pre>

---

@aymanhab commented on [Tue Aug 01 2017](https://github.com/opensim-org/opensim-gui/issues/68#issuecomment-319504762)

This obviously isn't a GUI issue until corresponding API issue is resolved

**Comment by tkuchida** [comment] 2017-08-05 06:26
Duplicate of #1762

**Closed by tkuchida** 2017-08-05 06:26 UTC
