### ISSUE TITLE
Consider redefining method(s) to re-express locations in this Frame rather than another Frame

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1412] opened 2016-11-18 00:07 UTC
In #1400 the following bug was discovered to express the location of a point location in ground (`pt`)  in the parent frame of a marker:

```cpp
pt2 = modelMarker.getParentFrame().findLocationInAnotherFrame(s, pt, aModel.getGround());
```

But `findLocationInAnotherFrame` is defined to express `pt` in *another* frame so it is a mistake to give it *Ground*. The correct usage is:

```cpp
pt2 = aModel.getGround().findLocationInAnotherFrame(s, pt, modelMarker.getParentFrame());
```

I find the language and documentation to be unambiguous, but I can see how it could be error prone  because the `location` and the `otherFrame` are, by definition of the method, not in the same *Frame*, which is somewhat counter-intuitive.

An alternate signature that may avoid this "dissonance", could be something like:
```cpp
// definition
Vec3 Frame::findLocationInThisFrame(const State&, const Vec3& otherPoint, const Frame& otherFrame)
...
// usage
pt2 = modelMarker.getParentFrame().findLocationInThisFrame(s, pt, aModel.getGround());
```
 where `pt` is expressed in `Ground` and the resulting `pt2` is expressed in the marker's parent `Frame` tasked to do the transformation. 

This would be a relatively easy fix if there is agreement that the current signature is confusing and the alternative is an improvement. I would prefer we made this change prior to releasing 4.0.

**Comment by chrisdembia** [comment] 2016-11-18 00:15
This might be relevant for how @carmichaelong is transitioning us off the SimbodyEngine, as I think he is often trying to express stations in Ground. We talked about adding a `frame.findLocationInGround(state, stationPosInThisFrame);`, which would be equivalent to `ground.findLocationInThisFrame(state, stationPosInOtherFrame, frame);` in the proposal above. I might be misremembering the details...

**Comment by tkuchida** [comment] 2016-11-18 00:30
Let the two frames be fA and fB, and let pX be the coordinates of point p expressed in frame fX. The problem is: _Given_ pA, fA, and fB, _Find_ pB. The current interface is
```cpp
pB = fA.findSomething(pA, fB)
```
which I agree is confusing because `pA` and `fB` are adjacent. The proposed change is better:
```cpp
pB = fB.findSomething(pA, fA)
```
however, frames `fA` and `fB` are still treated differently here (one is calling `translate` and the other is an argument) when it seems like they are conceptually similar ("translate from" and "translate to"). Whether the `find` method should be called from `fA` or `fB` is not structurally obvious. Would there be drawbacks to doing something like the following:
```cpp
static void Model::findSomething(const Frame& fA, const Vec3& pA,
                                 const Frame& fB,       Vec3& pB) const
```

**Comment by chrisdembia** [comment] 2016-11-18 00:36
@tkuchida very thorough analysis! Your proposal is similar to [`SimbodyEngine::getPosition`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/SimbodyEngine.h#L121), which `Frame::findSomething` is trying to replace. Though, having the function on Model would be an improvement.

**Comment by aseth1** [comment] 2016-11-18 00:56
@tkuchida thank you for restating the issue more clearly.

> Though, having the function on Model would be an improvement.

My preference would be not to load more methods on Model for capabilities that it doesn't implement or need to manage/coordinate itself. We could have the static method on Frame. It is more typical in C++ to have `pB = fB.findSomething(pA, fA)` where the object being invoked ('fB') is expected to operate (in this case `translate`) on its arguments even if arguments are of the same type.  I don't see why that is an issue.  I generally dislike methods that require a writable input argument (e.g. `pB`)  to return the output especially for lightweight operations like this one (i.e. not creating a complex data structure that is expected to be reused).

**Comment by tkuchida** [comment] 2016-11-18 01:19
> We could have the static method on Frame.

True. I hadn't considered the case where one would call `findSomething()` on a Frame that isn't part of a Model, but I guess that may be possible also.

>  I don't particularly see why that is an issue.

It isn't, but IMHO, a method with two pairs of arguments (`fA`, `pA`, `fB`, `pB`) is easier to parse than a method like `fB.findSomething(pA, fA)`. I think the reason is because there are two possible directions for writing the method, as you have shown:
```cpp
pB = fB.findPointCoordinatesWithRespectToMe(pA, fA) //case 1
pB = fA.findPointCoordinatesWithRespectToSomeOtherFrame(pA, fB) //case 2
```
I agree that case 1 is better, but the decision is still arbitrary and assumes the user understands the meaning of the method name. The proposed name (`findLocationInThisFrame()`) is still ambiguous: it isn't clear whether "this" refers to the frame that is calling the method or the frame that is passed in.

> I generally dislike methods that require a writable input argument (e.g. `pB`)  to return the output especially for lightweight operations like this one (i.e. not creating a complex data structure that is expected to be reused).

I don't share your aversion to such methods, and I would expect a sufficiently intelligent compiler to optimize out any unnecessary stuff. I agree in general, but I don't see what complex data structures would be created in this case since `pB` is being assigned to a `Vec3` anyway.

**Comment by tkuchida** [comment] 2016-11-18 07:21
Another approach could be to address the issue that `pA` is represented by a `Vec3`, which is analogous to a unitless number (the "unit" in this case is the frame relative to which the point's coordinates are expressed). Perhaps, then, the input could be a `std::pair<Vec3&, Frame&>` (or a struct named `PointInFrame` or something like that). The interface `pB = fB.findSomething( PointInFrame(pA, fA) );` would be reliably unambiguous IMHO, and the method could be named something simple like `Frame::findLocation()` or `Frame::findLocalCoordinates()` without issue.

**Comment by aseth1** [comment] 2016-12-01 19:37
Consensus is case 1.

**Comment by jenhicks** [comment] 2016-12-02 22:43
Is this an issue for 4.0? Who is going to work on this? @aseth1

**Comment by aseth1** [comment] 2016-12-03 02:21
@jenhicks It is an issue for 4.0 because it impacts the Frame API that is being introduced. It would be great if we didn't change it once we released it. The issue was raised in response to reviewer comments in #1400, which detected that the method was misused. 

We discussed changes in some length at the meeting yesterday and there seemed to be pros and cons for all proposals (including leaving it).  In principal this method is part of the replacement for `SimbodyEngine::transform` methods (which @carmichaelong is pursuing) and as such represents calculations that are more of a developer utility than user facing. 

For example, we already have `Point` as an abstraction that pairing of the `Vec3`  of coordinates with a `Frame` to form a meaningful spatial location. Furthermore, `Station` already has a non-ambiguous method:
`pInF = point.findLocationInFrame(s, frameF)`
 which is how most users will interact with a `Marker` or point of interest to re-express Markers in ground or an anatomical reference frame.

It is `Station::findLocationInFrame` and other methods in the API that use the Frame method, e.g.:
```cpp
SimTK::Vec3 Station::findLocationInFrame(const SimTK::State& s,
        const OpenSim::Frame& aFrame) const
{
    // transform location from the station's frame to the other frame
    return getParentFrame().findLocationInAnotherFrame(s, 
                                                get_location(), aFrame);
}
```

As @tkuchida points out, case 1 isn't perfect either, but it would avoid the issue with the input point `ptA` and frame `fB` being incongruent when it is easy to assume they are paired. 

Considering that we found 1 misuse of the method out of more than a dozen uses, also suggests it isn't a major issue. I also found the doxygen for `findLocationInAnotherFrame` to be unambiguous and it was easy to correct the mistake after reading it. 

Making the change is straightforward if we decide a change is warranted. I am happy to do it. What do you say? Change it or not? I am now leaning to leaving things as they are.

**Comment by jenhicks** [comment] 2016-12-05 17:16
Thanks for explaining the issue in more detail. I think that the current set-up is what I would expect, so I am ok with leaving it as-is.

**Comment by tkuchida** [comment] 2016-12-06 22:48
Perhaps a simple documentation change would help avoid some confusion. Currently, IntelliSense shows the following:

![findlocationinanotherframe](https://cloud.githubusercontent.com/assets/4203505/20946997/ec0458b0-bbc1-11e6-8ffa-f98586f07587.png)

I think it would be less ambiguous if we changed the variable names from
``` cpp
point_F, otherFrame
```
to
``` cpp
pointInCurrentFrame, otherFrame
```

**Comment by tkuchida** [comment] 2016-12-06 22:49
Oh, nevermind: if you're looking at the IntelliSense, you can just read the documentation.

**Comment by aseth1** [comment] 2016-12-07 21:24
@opensim-org/dev-team  I recommend closing this issue.

**Comment by chrisdembia** [comment] 2016-12-07 21:26
Sounds fine to me. We can always come back to it after some user testing.

**Comment by jenhicks** [comment] 2016-12-08 04:19
This sounds fine to me as well. I am closing, but as Chris mentioned, we can revisit.

**Closed by jenhicks** 2016-12-08 04:19 UTC
