### ISSUE TITLE
Zero DLLs found in directory

### ISSUE THREAD

**Issue by Vijesh-903** [opensim-org/opensim-core#3964] opened 2024-11-12 17:33 UTC
when i try to compile c++ code using Visual Studio  of opensim (opensim-core-main\cmake\OpenSimMacros.cmake) I get the error . where should I put the DLL and where I will get those??
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at cmake/OpenSimMacros.cmake:620 (message):
  Zero DLLs found in directory E:/Real time
  Biomechanics/opensim-core-main/../opensim_dependencies_install/ipopt/bin.		E:\Real time Biomechanics\opensim-core-main\cmake/OpenSimMacros.cmake	620

**Comment by aymanhab** [comment] 2024-11-15 19:16
You don't need to move anything, it's built into the build system. Likely you built dependencies without ipopt (OPENSIM_WITH_TROPTER, OPENSIM_WITH_CASADI OFF) and the opensim-core build configuration has both on. I'd suggest you make these flags consistent between the two builds. Since this is not a bug, will close this issue.

**Closed by aymanhab** 2024-11-15 19:16 UTC
