### ISSUE TITLE
Static Optimization results for "Strength of Simulation" example differ from 3.3

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2088] opened 2018-02-15 05:31 UTC
See "Strength of Simulation" example, Part I, Section C, first unordered list. Minimal example:
- open leg6dof9musc.osim
- lock pelvis_tilt, pelvis_tx, and pelvis_ty coordinates
- run Static (Motion = leg69_IK_swing.mot, Filter = 6 Hz)

**leg6dof9musc_StaticOptimization_activation.sto from 3.3:**
![](https://user-images.githubusercontent.com/4203505/36516040-1827b6aa-1731-11e8-900c-a4f8505c3526.png)

**leg6dof9musc_StaticOptimization_activation.sto from 4.0:**
![](https://user-images.githubusercontent.com/4203505/36516045-1df31764-1731-11e8-8f69-f7488392fd1f.png)

(AppVeyor artifact OpenSim-2fd23ef3-2018-02-20.zip)

**Comment by tkuchida** [comment] 2018-02-22 00:36
Possibly related to #2035

**Comment by tkuchida** [comment] 2018-02-22 02:03
Update: activations greater than 1 were caused by interpolation in Excel. Main reproducibility issue persists.

**Comment by chrisdembia** [comment] 2018-02-22 04:17
Verified on Mac  with OpenSim 2fd23ef-2018-02-20:

<img width="871" alt="screen shot 2018-02-21 at 8 16 40 pm" src="https://user-images.githubusercontent.com/846001/36520142-26b2b874-1744-11e8-8b2f-f627c59682b5.png">

**Comment by tkuchida** [comment] 2018-02-26 17:52
Not a model-specific issue. Tested with arm26 model on OpenSim-2416f17a-2018-02-25.zip ("OpenSim 4.0 User Experience and Feedback Session" version):

**3.3**
![](https://user-images.githubusercontent.com/4203505/36686210-96d9a3c6-1ada-11e8-80f3-5790b3faddba.png)

**4.0**
![](https://user-images.githubusercontent.com/4203505/36686222-9da32ba0-1ada-11e8-9365-ee703a653984.png)

**Comment by tkuchida** [comment] 2018-02-26 18:19
**Solution found, for arm26 model**
The `min_control` property for each muscle (Thelen2003Muscle) has a value of 0 in the .osim file but 4.0 changes these values to 0.01 when it loads the model, *without telling the user*. The user is unable to change these values back to 0:

![](https://user-images.githubusercontent.com/4203505/36687079-537732da-1add-11e8-9b01-94a77462aa14.png)

I opened the model in 3.3 and changed the `min_control` property values to 0.01 (to replicate what 4.0 does when opening the model) and now get the same results as in 4.0:

![](https://user-images.githubusercontent.com/4203505/36687414-6346600e-1ade-11e8-92af-a91a4a98a870.png)

**Comment by carmichaelong** [comment] 2018-02-26 18:41
**Solution for Joint Reaction Example, Static Optimization differences**

The model already had the `min_control` values at 0.01, but I re-ran it in 3.3 and got the same answers as 4.0 (compare with above):
![image](https://user-images.githubusercontent.com/7455790/36688491-7b229d7a-1ae1-11e8-8469-5282334a0b82.png)
 
Fix may be to just update the reference values, since they seem to be from 2.4.

**Comment by tkuchida** [comment] 2018-02-26 19:04
@carmichaelong: Please file a new Issue if reference file should be updated.
**Note:** Above solution for arm26 model does *not* work for leg6dof9musc model; original Issue persists.

**Comment by clnsmith** [comment] 2018-08-06 14:34
Hi Guys,

I'm also seeing a difference between OpenSim 3.3 and 4.0 for static optimization for the same input data. I'm using the same walking data released with Apoorva's paper as input to both versions and adding the cmc_actuators.xml as additional actuators. 

If I look at the activations of the reserve actutators at the pelvis, there is obviously something going on in 4.0:

Version 3.3
![image](https://user-images.githubusercontent.com/1234687/43721879-4f2d1e8e-9994-11e8-97e4-33154fbc81ba.png)

Version 4.0
![image](https://user-images.githubusercontent.com/1234687/43721905-5f920686-9994-11e8-9755-5ac8cffb4d59.png)

I've been digging through the source code, but have not been able to find the main cause of this issue.

One small thing I found: 
https://github.com/opensim-org/opensim-core/blob/f8e7b4f047e2e66b23c1895a63995200b8f33b0d/OpenSim/Analyses/StaticOptimization.cpp#L567

       _accelerationIndices.setSize(0);
        auto coordinates = _modelWorkingCopy->getCoordinatesInMultibodyTreeOrder();
        for(size_t i=0u; i<coordinates.size(); ++i) {
            const Coordinate& coord = *coordinates[i];
            if(!coord.isConstrained(sWorkingCopy)) {
                Array<int> inds = _statesStore->
                    getColumnIndicesForIdentifier(coord.getName()) ;
                _accelerationIndices.append(inds[0]);
            }
        }

here  _accelerationIndices is actually full of zeros because the name of the column in _statesStore is actually coord.getName() + "/value". So  getColumnIndicesForIdentifier returns an Array of size 0, and when you call inds[0] it gives a 0 (which is strange to me since it is a size 0 Array, so it should be an error?)

side note, maybe there should be a function coord.getValueName() to overcome this, just like there is coord.getSpeedName().

In the end this doesn't cause the main issue in the optimization because _accelerationIndices (StaticOptimization.cpp member) is only used to compute the number of constraints, which is still done correctly. In StaticOptimizationTarget.cpp, _acclerationIndices is recomputed (correctly this time), and these are actually used in the computation of the optimization constraints. A small issue will occur in Static Optimization.cpp in the error checking if the optimization fails:
https://github.com/opensim-org/opensim-core/blob/f8e7b4f047e2e66b23c1895a63995200b8f33b0d/OpenSim/Analyses/StaticOptimization.cpp#L456

I'll keep you posted if I find the main issue, but I'm pretty stumped at the moment.

**Comment by clnsmith** [comment] 2018-08-06 19:11
Made some progress... still don't know the underlying cause though.

I am still finding differences between 3.3 and 4.0 for static optimization even with:
-no external loads
-no filtering kinematics
-no muscles (coordinate actuator at each joint, so it is not a redundant system anymore, just computing the actuator activations to satisfy the acceleration constraints)

For this condition, if I run a kinematics analysis (in the respective GUI versions of the software). I see no differences in the q's and u's, but there are differences in the udots between the 3.3 and 4.0 versions. 

One other strange thing is that for 4.0 kinematics analysis (not 3.3), the "knee_angle_r_beta" and "knee_angle_l_beta" (coupled to the knee_angle_r and _l) the q's are written to the .sto in radians, while the rest of the angles in the file are written in degrees. The u's are written correctly for this coordinate (in degrees) and then the udots are again in radians (while all the other angles are in degrees).

**Comment by aymanhab** [comment] 2018-08-06 19:14
Maybe another symptom of https://github.com/opensim-org/opensim-core/issues/2240

**Comment by aseth1** [comment] 2018-08-06 20:25
@clnsmith the `MotionType` assigned to *knee_angle_r_beta* and *knee_angle_l_beta* is inconsistent between 3.3 and 4.0. In 3.3 we allowed the user/modeler specify the `MotionType`, which was wrong. In 4.0 we have a systematic way to determine `MotionType` that requires the spatial motion related to he coordinate to be pure Rotational(Translational) to be assigned that type. This is not the case for the *_beta* variables which are converted to patella rotations via a spline.  That's why 4.0 does not interpet them as angles (so not radians) and are not converted to degrees.

I will test if this is the underlying cause for the differences in the 3.3 vs 4.0 solutions.

**Comment by aseth1** [comment] 2018-08-06 21:31
If we run IK in 4.0 or if I manually undo the degrees conversion of the motion from 3.3. for the *kneed_angle_#_beta* coordinates I get the same answer that matches @clnsmith's post of 3.3 results:

![image](https://user-images.githubusercontent.com/6494122/43741645-f4c32f02-9983-11e8-82a0-128da96402e4.png)

So it seems the issue is the interpretation of the coordinate value that is affecting the results.
We now have the problem that motion files in 3.3 could be incorrect in 4.0.

I think we need to do #2240.

AFAICT the discrepancy reported in this issue is not related to a bug in SO.

**Comment by aseth1** [comment] 2018-08-06 21:49
The `MotionType` issue also explains @tkuchida's original issue. Both the erroneous 4.0 results and the original 3.3 results were generated in 4.0 by using the 33 motion file or performing IK in 4.0, respectively.
  
![image](https://user-images.githubusercontent.com/6494122/43742584-598e4c7a-9987-11e8-9c6d-917974562be6.png)

![image](https://user-images.githubusercontent.com/6494122/43742650-8d0fcc36-9987-11e8-8b9c-e490e0e6be8f.png)

**Comment by jenhicks** [comment] 2018-08-06 21:56
Thanks for investigating the issue, @aseth1 . To make sure that I completely understand the issue and ramifications for users ... if labeling the MotionType as rotational was incorrect in 3.3, why is that you get the same answers in both 3.3 and 4.0 as long as you run IK and SO in the same software versions? (i.e., what are the specific cases where labeling a couple motion as rotation gives incorrect answers?)

**Comment by aseth1** [comment] 2018-08-06 23:45
> what are the specific cases where labeling a couple motion as rotation gives incorrect answers?

Good question. I will try to answer it on #2240.

**Comment by clnsmith** [comment] 2018-08-07 12:43
Yes this is working for me now too. I just went through the whole workflow (Scale, IK, SO) in 4.0 and the results look good. 

Thanks for the explanation on the MotionType. I agree it makes sense that it should not be user defined.

**Comment by jenhicks** [comment] 2018-08-08 20:36
@aseth1 What needs verifying here?

**Comment by aseth1** [comment] 2018-08-09 03:33
I guess between @clnsmith and myself, we verified the cause. #2243  will attempt to address. I will move this into In Progress until #2243 is merged.

**Comment by jenhicks** [comment] 2018-08-10 21:43
Closing this issue since we created issues to add warning for users and update files we distribute.

**Closed by jenhicks** 2018-08-10 21:43 UTC
Labels: Examples, Feb 26 User Session Day-of
