### ISSUE TITLE
Inaugural build compiles but fails a number of test?

### ISSUE THREAD

**Issue by Bazmundi** [opensim-org/opensim-core#3802] opened 2024-06-08 05:49 UTC
Gist [here](https://gist.github.com/Bazmundi/92cf5cb94621828bc944585ec75a72aa)

basically compiled from https://github.com/opensim-org/opensim-core main

failed some of the python tests at the end

Compiled on Ubuntu 22.04

Python 3.11 installed.

**Comment by tkuchida** [comment] 2024-06-08 12:07
The errors all seem to be `version GLIBCXX_3.4.30 not found`. Perhaps try https://stackoverflow.com/questions/72540359/glibcxx-3-4-30-not-found-for-librosa-in-conda-virtual-environment-after-tryin

**Comment by nickbianco** [comment] 2024-06-10 17:17
Closing since this a conda/Python environment issue, not a bug.

**Closed by nickbianco** 2024-06-10 17:17 UTC
